### ISSUE TITLE
In occupant prep script, add support for creating sites out of non-civic addresses

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#10]
Currently, the occupant list import script creates a ready-to-load occupant list. Enhance the script so that it also creates a ready-to-load non-civic-site list that can be appended to the sites.csv file. An occupant has a non-civic address if its isNonCivic flag is set to true.

**Comment by gleeming** [comment]
New STREET_ADDRESS field in the GSR export is now supported for NCAP site candidate processing.  This is concatenated with the ITN locality name in which the occupant location resides to form the batch addressString.

**Comment by mraross** [comment]
verified
