### ISSUE TITLE
in route planner, add support for GPX output format

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#104]

**Comment by cmhodgson** [comment]
Is there a specific requirement for this format? An example of what the GPX format should look like for this application/requirement?

**Comment by mraross** [comment]
No identified business requirement. Its just one of the formats that graph hopper currently supports.

**Comment by cmhodgson** [comment]
We are not using graphhopper to do any output formatting. We would be rolling our own to some degree, potentially there is some java library support for this to minimize the effort, possibly at the cost of some flexibility, eg. if we want to format the GPX in a particular way.

**Comment by mraross** [comment]
Issue moved to [bcgov/ols-router #52](https://github.com/bcgov/ols-router/issues/52) via [**ZenHub**](https://www.zenhub.com/)
