### ISSUE TITLE
Add support for a ferry wait time delay/penalty

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#108]

**Comment by cmhodgson** [comment]
It is not clear how long the delay should be, particularly for the less-regular ferries, but given the delay it can be added.
This approach is an alternative to the schedule-based approach of another ticket; this approach doesn't take into account time of day, and thus is appropriate to use when none is specified.

**Comment by mraross** [comment]
We could probably classify a given ferry route into hourly or bi-hourly and use this information to come up with a more reasonable wait time.

**Comment by cmhodgson** [comment]
I'm thinking about services that are twice-daily, daily, or even less frequent - what is the "average wait time" for the ferry from Port Hardy to Prince Rupert that leaves only every second Saturday? Not sure if it is meaningful to do anything here at all? It would then be inconsistent with the other ferries where we do add the wait time. Google just flags the route with something like "this route uses Ferries, be sure to check the schedule", perhaps that is an alternative approach?

**Comment by mraross** [comment]
Not needed since  ferry schedule will be taken into account when doing time-dependent routing.
