### ISSUE TITLE
Street name spelled wrong fault not being generated for misspelled street names

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#114]
The following address:
   Prince 

returns the following match:

   Price, Indian Arm, BC

with no street name spelled wrong fault.

**Comment by gleeming** [comment]
Also from JTrac ticket BGEO-304 something similar was fixed in v1.3 but is now not working again.  Test case was Community Center Rd, Grand Forks, BC (should be a fault for street name spelled wrong: Centre)

**Comment by cmhodgson** [comment]
Fixed locally.

**Comment by cmhodgson** [comment]
Confirmed Fixed in delivery.

**Comment by mraross** [comment]
Verified using the following addresses:

Community Center Rd, Grand Forks, BC
30 Frith Cres, Mackenzie, BC
30 Firht Cres, Macknezie, BC
30 Fifth Cres, Mackenzie, BC

**Comment by mraross** [comment]
Verified in delivery using Prince plus addresses above.
