### ISSUE TITLE
in geocoder and router, remove deprecated X-*CSP headers

### ISSUE THREAD

**Issue by ll911** [bcgov/api-specs#116]
https://content-security-policy.com/ 
update to CSP and remove deprecated X-* CSP headers.

**Comment by cmhodgson** [comment]
This is a trivial change for the geocoder and router rest interfaces.

*IF* this affects the batch geocoder plugin, that must be changed in CPF, as a CPF plugin has no control over the headers returned.

**Comment by cmhodgson** [comment]
Done.

**Comment by cmhodgson** [comment]
Confirmed in delivery.

**Comment by mraross** [comment]
Verified
