### ISSUE TITLE
geomark doc site display problem

### ISSUE THREAD

**Issue by ll911** [bcgov/api-specs#117]
http://apps.gov.bc.ca/pub/geomark/docs/
<img width="782" alt="screen shot 2016-11-30 at 8 10 08 pm" src="https://cloud.githubusercontent.com/assets/11949273/20781633/28bd06c2-b739-11e6-9476-c015b8e48107.png">

**Comment by BK01** [comment]
Issue present in Geomark version 5.0.1

**Comment by BK01** [comment]
@mraross FYI this issue can be closed

**Comment by mraross** [comment]
Confirmed
