### ISSUE TITLE
in geomark, remove deprecated X-*CSP headers

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#118]
https://content-security-policy.com/
update to CSP and remove deprecated X-* CSP headers.

**Comment by pauldaustin** [comment]
Michael,

None of my code uses the CSP Headers.

Paul

**Comment by mraross** [comment]
Great. Please move resolved issues to Review/QA, not DONE.

**Comment by ll911** [comment]
if x-* csp headers not used, please remove them from geomark.

Sent from my iPhone

On Dec 1, 2016, at 11:43 AM, Michael Ross <notifications@github.com<mailto:notifications@github.com>> wrote:


Great. Please move resolved issues to Review/QA, not DONE.

-

**Comment by pauldaustin** [comment]
Please show a response from geomark that is returning the X-*CSP headers

**Comment by ll911** [comment]
confirmed X-* CSP header not used.

```bash
curl -I -X GET "http://apps.gov.bc.ca/pub/geomark/geomarks/gm-abcdefghijklmnopqrstuv0bcislands.json?srid=4326"
HTTP/1.1 200 OK
Date: Thu, 01 Dec 2016 21:58:36 GMT
Server: Apache-Coyote/1.1
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-XSS-Protection: 1; mode=block
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
Access-Control-Allow-Origin: *
Content-Type: application/json;charset=utf-8
Content-Language: en
Transfer-Encoding: chunked
