### ISSUE TITLE
Street level match doesn't always return a point on the street

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#121]
```Hwy 97B , Salmon Arm, BC```

returns a point on a road segment of HWY 97B

```Hwy 97B SE, Salmon Arm, BC```

returns a point that isn't on a road segment of HWY 97B

**Comment by gleeming** [comment]
It does return a point that is on a road segment named Hwy 97B SE in ITN.  It is the closest vertex to the centroid of all Hwy 97B SE segments in Salmon Arm.  For this particular case, that vertex happens to be located in the middle of a large strata complex at 2500 Hwy 97B SE,

**Comment by gleeming** [comment]
One option would be to ignore strata class roads when computing street locality centroids

**Comment by mraross** [comment]
Verified.
