### ISSUE TITLE
in geocoder/addresses, add support for a STREET_DIRECTION.notMatchedInHighway fault

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#122]
There are many highway addresses from municipalities that have superfluous streetDirections according to  the DRA. These streetDirections will get otherwise valid highway addresses rejected during address prep. We can "fix" the data in address prep using DRA as a reference or change the way the geocoder handles a highway direction fault as follows:

Allow a highway street direction to be not matched without a penalty. Implement as a HighwayDirection.notMatched fault that can have its own penalty which is defaulted to zero. This allows the non-highway streetDirection.notMatched fault to still have a positive penalty.

Currently the query address:

12621 Hwy 99 N, Lillooet, BC

returns the following:

12621 Hwy 99, Lillooet, BC

and a fault of [STREET_DIRECTION.notMatched:2]

After this enhancement is implemented, the geocoder will return the same fullAddress but a fault of [STREET_DIRECTION.notMatchedInHighway:0]

**Comment by mraross** [comment]
When reference highway address improves, we can increase the fault penalty to get more comprehensive error reporting.

**Comment by cmhodgson** [comment]
After discussion with Michael, I had an idea for an alternative approach; after further discussion with Graeme, my idea won't work. This approach does fix the most common problem identified (reference address data with highway directionals that aren't present in the ITN).

Any approach that handles street name (directional) manipulations in the block assignment and address resolution step opens a significant new can of worms as the current process is based on street name IDs only. I don't think that where we want to go at this time.

**Comment by cmhodgson** [comment]
This is done as per the original approach.

**Comment by cmhodgson** [comment]
This is done LOCALLY. It still needs to be delivered, tested, verified.

**Comment by cmhodgson** [comment]
Confirmed in delivery.

**Comment by mraross** [comment]
Verified using the following addresses:

12621 Hwy 99 N, Lillooet, BC
8930 Cariboo Hwy S, Pineview FFG, BC

**Comment by mraross** [comment]
verified in delivery
