### ISSUE TITLE
Raise a fault when a street direction or street type is entered as a prefix instead of a suffix or vice-versa

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#132]
If you geocode:

   4216 E 51 Ave, Fort Nelson, BC

you get the following and no fault:

    4216 51 Ave E, Fort Nelson, BC

It should return the following fault:

   STREET_DIRECTION.notPrefix

The reverse case can be covered by the following:

   STREET_DIRECTION.notSuffix

Add similar faults for STREET_TYPE as well (e.g., STREET_TYPE.notPrefix, STREET_TYPE.notSuffix)

**Comment by cmhodgson** [comment]
This shouldn't be a big deal to add.
Do you want to do something similar for street types?

**Comment by mraross** [comment]
Sure. Treating both street_direction and street_type similarly makes perfect sense. So how about a default penalty of zero. I don't really want to mess with the scoring right now.

**Comment by cmhodgson** [comment]
This actually required a bigger effort than I had expected as it required changes at the parser level to separately record prefix and suffix directions and types. Looks to be working well though.

**Comment by cmhodgson** [comment]
Confirmed in Delivery.

**Comment by mraross** [comment]
Verified with the following addresses:

4216 E 51 Ave, Fort Nelson, BC
2186 Marine Dr SW, Vancouver, BC

**Comment by mraross** [comment]
Verified in delivery
