### ISSUE TITLE
in address and occupant finder widgets, allow developer to configure the choice of target geocoder (e.g., public, gated)

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#136]
Could add an apikey config parm. If apikey parm is set, call the gated geocoder with the apikey in the request header; otherwise call the public geocoder

**Comment by ll911** [comment]
apikey should be part of header not parm

**Comment by mraross** [comment]
It is a parm of the widget itself and part of the geocode request header.

**Comment by ll911** [comment]
that process needs to be on server side as resource proxy, otherwise, the apikey is exposed to client browser.

**Comment by mraross** [comment]
Confirmed and closed
