### ISSUE TITLE
in occupants/near, make tags optional. if no tags supplied, return occupants of any type

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#14]
cmhodgson wrote:

"We discussed that this was an additional feature that wasn't originally planned and being non-trivial we should push it to 2.1 or later."

**Comment by cmhodgson** [comment]
This required creating a spatial index of all occupants. This didn't cause a significant increase in memory usage.

**Comment by cmhodgson** [comment]
Working in delivery:
http://delivery.apps.gov.bc.ca/pub/geocoder/occupants/near.xhtml?point=-123.3878629,%2048.5326952&maxResults=10

**Comment by mraross** [comment]
Verified in delivery

**Comment by mraross** [comment]
Verified in Test
