### ISSUE TITLE
In batch address list submitter, use multipart/form-data instead of regular posted forms

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#140]
In the new version of CPF, the contract of the interface didn't change (it was always mutlipart/form-data). The previous version had an undocumented feature that allowed it to also accept regular posted forms. In the new version, a performance related enhancement was made that expects the request to be a MultiPart request so now, a regular posted form causes a ClassCastException. For more info, see:

https://github.com/bcgov/cpf/issues/56#issuecomment-277322761

Urgent fix is required to allow ICIS to QA municipal address data.

**Comment by cmhodgson** [comment]
The fix, in short, is to replace a single line:
`	fields['inputDataUrl'] = filename`
with
`	files = {'inputDataUrl': ('', filename)}`

**Comment by cmhodgson** [comment]
Where did the repository go for devkit? It was previously at https://gogs.data.gov.bc.ca/dbcols/geocoder-devkit ?

**Comment by cmhodgson** [comment]
Fix committed to http://github.com/bcgov/ols-devkit (gh-pages branch).

**Comment by mraross** [comment]
moved to ols-devkit repo
