### ISSUE TITLE
in delivery, online geocoder fails on intersection addresses

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#144]
http://delivery.apps.gov.bc.ca/pub/geocoder/addresses.kml?addressString=douglas+st+and+Victoria+Rd%2CChemainus%2Cbc

http://delivery.apps.gov.bc.ca/pub/geocoder/addresses.kml?&addressString=douglas+st+and+yates+st+victoria+bc

**Comment by cmhodgson** [comment]
This is a bug related to the parsing changes required for #132. I've fixed this locally. I believe it only affects intersection matches (with streets that have either no type or no direction). Please continue testing, we can deliver this fix with any others found.

**Comment by cmhodgson** [comment]
Confirmed in Delivery.

**Comment by mraross** [comment]
Verified in delivery
