### ISSUE TITLE
In delivery, province-level match point in ocean instead of middle of province

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#145]
Rural Rt 3 1875 Sandstone Dr Penticton, BC returns an ocean point

Rural Rte 3 1875 Sandstone Dr Penticton, BC returns a point in Prince George

**Comment by cmhodgson** [comment]
This bug has probably been here a while. The "fallback location" gets geocoded and stored at startup, then reused for every case of a no-result query; when it get's reprojected to lat-long; that value gets stored, but is still expected to be albers, for the next use. The point we were getting was essentially albers 0,0 . I've fixed this by cloning the fallback match before using it.

**Comment by cmhodgson** [comment]
Confirmed in delivery.

**Comment by mraross** [comment]
Confirmed in delivery.
