### ISSUE TITLE
Study approaches to supporting a reference address input format that makes it easy to define building complexes

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#146]
To eliminate the need for superSiteIDs when defining complexes in data files from address authorities, add support for a superFullSiteDescriptor. A superFullSiteDescriptor is the fullSiteDescriptor of a site's superSite with a "part-of" delimeter separating each level of hierachy.  For example Royal Miracle Hospital has a Patient Care Centre with eight floors. Each floor has north and south wings. Here is some sample data using "--" as the part-of separator:

unitDescriptor,unitNumber,unitNumberSuffix,siteName,superFullSiteDescriptor
,,,Royal Miracle Hospital,
,,,Patient Care Centre,Royal Miracle Hospital
RM,100,N,,Patient Care Centre--Royal Miracle Hospital
RM,200,N,,Patient Care Centre--Royal Miracle Hospital
RM,300,N,,Patient Care Centre--Royal Miracle Hospital
RM,400,N,,Patient Care Centre--Royal Miracle Hospital
RM,500,N,,Patient Care Centre--Royal Miracle Hospital
RM,600,N,,Patient Care Centre--Royal Miracle Hospital
RM,700,N,,Patient Care Centre--Royal Miracle Hospital
RM,800,N,,Patient Care Centre--Royal Miracle Hospital

The fullSiteDescriptor of the last entry above is:

RM 800N, Patient Care Centre, Royal Miracle Hospital --

If we also add support for unit ranges, we can define all rooms succinctly as follows:

unitDescriptor,unitNumber,unitNumberSuffix,unitRange,siteName,superFullSiteDescriptor
,,,Royal Miracle Hospital,
,,,Patient Care Centre,Royal Miracle Hospital
RM,,,"100-199,200-299,300-399,400-499,500-599,600-699,700-799,800-899,900-999",N,Patient Care Centre--Royal Miracle Hospital
RM,,,"100-199,200-299,300-399,400-499,500-599,600-699,700-799,800-899,900-999",S,Patient Care Centre--Royal Miracle Hospital

Here's an example of an airport with three terminals (A,B,C) and 30 gates in each terminal:

unitDescriptor,unitNumber,unitNumberSuffix,unitRange,siteName,superFullSiteDescriptor
,,,,Big International Airport,
Terminal,A,,,,Big International Airport
Gate,,,1-30,,Terminal A--Big International Airport
Terminal,B,,,,Big International Airport
Gate,,,1-30,,Terminal B--Big International Airport
Terminal,B,,,,Big International Airport
Gate,,,1-30,,Terminal C--Big International Airport

Here is an example of  a condo complex with three named buildings. Each building has 4 floors and 20 units on each floor. There is also unit 100A in each building.

unitDescriptor,unitNumber,unitNumberSuffix,unitRange,siteName,superFullSiteDescriptor
,,,,Forest Villa,
Maple Building,,,,Forest Villa
Oak Building,,,,Forest Villa
Sequoia Building,,,,Forest Villa
Suite,,,"100-119,200-219,300-319,400-419",,"Maple Building--Forest Villa"
Suite,,,"100-119,200-219,300-319,400-419",,"Oak Building--Forest Villa"
Suite,,,"100-119,200-219,300-319,400-419",,"Sequoia Building--Forest Villa"
Suite,,,100,A,"Maple Building--Forest Villa"
Suite,,,100,A,"Oak Building--Forest Villa"
Suite,,,100,A,"Sequoia Building--Forest Villa"

**Comment by gleeming** [comment]
Added a timeboxed estimate for investigating the creation and reconciliation of sites with an additional hierarchy level.

**Comment by gleeming** [comment]
The study was completed and in doing so an approach was implemented and tested.  There is now a superFullSiteDescriptor field in the site prep files.  The DataBC input format will be the first to support this extended descriptor usage for modeling building complexes

**Comment by mraross** [comment]
Verified
