### ISSUE TITLE
Add an /occupants/tags resource to support tag autocompletion in devkit

### ISSUE THREAD

**Issue by cmhodgson** [bcgov/api-specs#147]
Partial/prefix matching to support autocomplete widget - as needed by devkit

**Comment by mraross** [comment]
Use start-anchored word prefix matching to avoid meaningless matches. Look at example 4 in the following:
https://sean.is/poppin/tags

taggle clearly uses substring matching without regard for position in the tag string. This adds a lot of noise to a simple lookup. I would prefer if we limited searching to beginnings of words (e.g., "ma" should match "applied mathematics" but not "information"

**Comment by mraross** [comment]
What output formats should be supported? For sure json and xml. Maybe CSV. Not sure if any other formats are useful.

**Comment by cmhodgson** [comment]
I am returning a list of strings. I was only going to support json, for ease of use in the widget.  XML would technically require a schema... I think it is overkill. csv would just be a list of strings, one per line, easy, possibly useful. I guess we could wrap in html but I don't really see the point.

**Comment by mraross** [comment]
Ok, just json for now then.

**Comment by cmhodgson** [comment]
Here is an example of the results:
/geocoder/occupants/tags.json?tag=s&maxResults=-1

["schools","seaplane","secondary","services","shipping","shipyard","educational services","elementary and secondary schools","employment services","golden spruce","protective services","provincial protective services","weigh scale"]

**Comment by cmhodgson** [comment]
Confirmed in delivery. here are a couple of URLs to start with:
First 8 tags including words that start with "s":
http://delivery.apps.gov.bc.ca/pub/geocoder/occupants/tags.json?tag=s&maxResults=8

All tags:
http://delivery.apps.gov.bc.ca/pub/geocoder/occupants/tags.json?maxResults=-1

**Comment by mraross** [comment]
Verified in delivery
