### ISSUE TITLE
Improve performance of router/betweenPairs

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#148]
Our web server timeout limit is about one minute. Currently, about 100 fastest/shortest routes over long distances can be computed. Implement an optimized algorithm that can share partial routes.

**Comment by mraross** [comment]
For example, given 2 origin points and 14 destination points, do 2 marches, march 1 from origin point 1 to all 14 destination points then march 2 from origin point 1 to all 14 destination points.
If there are many toPoints, the graph voronoi algorithm can save a lot of execution time because graph edges are evaluated once and results shared amongst all shortest routes in progress for a given origin point. For example, in ACDF, the distance from a prospective lab to up to 180 existing lab locations has to be computed. Use of the graph voronoi will reduce execution time from minutes to seconds.

**Comment by mraross** [comment]
The graph voronoi could be a useful algorithm: https://web.engr.oregonstate.edu/~erwig/papers/GraphVoronoi_Networks00.pdf

**Comment by cmhodgson** [comment]
The graph voronoi paper (which I hadn't read until now but I had assumed existed) describes exactly how my test implementation works - the "parallel dijkstra" is precisely what I've done.

**Comment by mraross** [comment]
Cool,

**Comment by cmhodgson** [comment]
This is done and works fantastically.

**Comment by cmhodgson** [comment]
Deployed to delivery now.

**Comment by mraross** [comment]
Verified
