### ISSUE TITLE
Structured address with an unknown unitDesignator but an otherwise valid civic address returns no match

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#15]
pramsay wrote:

"The same address, supplied to the geocoder in different ways, leads to different match precisions.

Broken into parts, the geocoder only returns a 'PROVINCE' level match result.

http://apps.gov.bc.ca/pub/geocoder/addresses.xhtml?&unitDesignator=BASEM&streetName=70A&streetType=AVE&civicNumber=14375&localityName=SURREY&streetDirection=&province=BC

But glued together into a string, the geocoder happily consumes it (and produces the very parts used above) and provides a 'CIVIC_NUMBER' level of precision.

http://apps.gov.bc.ca/pub/geocoder/addresses.xhtml?addressString=BASEM%20--%2014375%2070A%20AVE%2C%20SURREY%2C%20BC"

**Comment by mraross** [comment]
The structured result should return the same as the unstructured result except no siteName and a unitDesignator notMatched error.

A valid unitDesignator works as expected:
```
http://apps.gov.bc.ca/pub/geocoder/addresses.xhtml?streetName=70A&streetType=AVE&unitDesignator=BSMT&civicNumber=14375&localityName=SURREY&streetDirection=&province=BC
```

**Comment by cmhodgson** [comment]
We can handle this case by adding an abbreviation mapping from basem to basement. There is a larger, more general problem with the structured address parsing mechanism that prevents matching when any input field does not contain a valid/known value for that field, but this will require more time to fix and it is not a priority at this time.

**Comment by mraross** [comment]
Added abbreviation BASEM ==> Basement to catch this variant of unitDesignator BSMT

**Comment by mraross** [comment]
Verified using test query above

**Comment by mraross** [comment]
Verified in test
