### ISSUE TITLE
Spatially index access points and use when accessPoints are requested in reverse geocoding

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#150]
spatially index site accessPoints and use this index in a reverse geocoding request that specifies accessPoints. For example:
  sites/nearest.kml?locationDescriptor=accessPoint
  sites/near.geojson?locationDescriptor=accessPoint
  sites/within.csv?locationDescriptor=accessPoint

Reverse geocoding requests for any other locationDescriptor should use the parcelPoint/rooftopPoint/frontDoorPoint index

**Comment by mraross** [comment]
Parcel points are often far from the road the address is associated with. This can easily lead to a confusing nearest site. Also, a single parcel may have a single parcelPoint but multiple accessPoints, each on a different street. For example, Beacon Hill Park in Victoria has the same parcelPoint for its five addresses:

189 Douglas St
100 Cook St
150 Cook St
240 Bridge Way
160 Nursery Rd

**Comment by cmhodgson** [comment]
This is implemented and works nicely, you can compare some of the problem cases before where the access point should have been in view but because the site point was not, the access point was not displayed, but with this change it is working beautifully.

**Comment by mraross** [comment]
Confirmed in delivery
