### ISSUE TITLE
missing data: Fairway Hills Rd  Blind Bay, BC

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/api-specs#154]
2688 Fairway Hills Rd  Blind Bay, BC is a valid address but the geocoder cannot find it and makes a match that scores 63, which is 8 minutes drive away.  DRA must be missing this data?
![blind_bay_low_score](https://cloud.githubusercontent.com/assets/26335003/23813589/672655fe-0594-11e7-8dbd-5a387765fef3.JPG)

**Comment by NicoledeGreef** [comment]
red circled point is true location (commercial building) whereas the matched address that scored only 63 is the point of origin.

**Comment by mraross** [comment]
![geocoder_672 mar 10 13 35](https://cloud.githubusercontent.com/assets/11318574/23814018/8601ded8-0596-11e7-81b7-0dec470d9c10.jpg)

**Comment by mraross** [comment]
DRA calls the road Golf Course Dr and Google calls it Fairway Hills Rd.

**Comment by gleeming** [comment]
Are you sure it a current, valid address?

DRA/ITN used to have a Fairway Hills Rd but a lot of the streets in Blind Bay got renamed.  The access point off the highway also has been recently updated as can be seen in the screen shot above.  This change not reflected in the Google Maps or Street View data (but can be seen in their more recent orthos).

Golf Course Dr matches up with the latest BC Assessment, Address BC and the official Columbia Shuswap RD web map.  So to me it looks like Google is out of date and the address in question has been renamed.

**Comment by gleeming** [comment]
From an ITN JIRA ticket from almost 3 years ago: "Fairway Hills Rd is now known as Golf Course Dr".  This was intiated by a contact with email at csrd.bc.ca

**Comment by NicoledeGreef** [comment]
The address came to us through an application to put a Diagnostic Facility in the strip mall.  The road may have been renamed but I supp
![golf course drive vs fairway hills rd](https://cloud.githubusercontent.com/assets/26335003/23868799/0e9fc914-07de-11e7-959c-632c4d20a9b2.JPG)
ose whomever submitted the application is not using it yet.

2688 Golf Course Drive does not get the right location in either the geocoder or google maps.  Might there be a new address range to go with the street name change?

**Comment by gleeming** [comment]
Yes, the civic numbers changed too, and so did the ranges in ITN to correspond.  For example Our Lady of the Lake Catholic church was at 2740 Fairway Hills Rd and is now addressed as 2385 Golf Course Dr.

**Comment by cogborne** [comment]
So the address being asked for is in fact an invalid address as the the mall was readdressed in 2014 to 2425 - 2411 Golf Course Rd

**Comment by NicoledeGreef** [comment]
Thanks all - will close this ticket.
