### ISSUE TITLE
In geocoder, add sites/atRandom resource

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#159]
sites/atRandom picks up to maxResults sites at random within the bbox specified
Parameters include:
locationDescriptor - type of location to return
maxResults - maximum number of sites to return.  Fewer than maxResults will be returned if there are fewer sites within the bbox than maxResults ; Default is 1.
bbox - bounding box to choose sites from
outputSRS - Desired map projection, stated as an EPSG code, of the resulting site locations.
withReplacement - true if selection with replacement (e.g., allow duplicates); false otherwise (e.g., don't allow duplicates)

This resource is needed to compute meaningful statistics on the entire address list for comparison to the address lists used in other geocoders (e.g., google maps, bing maps, AGOL).

**Comment by cmhodgson** [comment]
Do we really need random? Or would arbitrary suffice? There is a hashtable of all sites, by ID, so we could go a random distance into that table and grab one. But with the localities constraint, this is more difficult. We'd need a list of all sites in each locality, this is another chunk of memory taken up for this purpose. If arbitrary would suffice, then we could randomly pick a locality from the list (with no regard for the number of sites in each locality) and then pick the first site on the first segment (or nth on nth segment) - but then you always get the same one (or one of a short list) for a given locality. The problem is that we don't know how many sites are in each locality, and we don't have a random-access way to get at them. 

Does every site need to have a chance of being selected? Do they all need to have an equal chance?

**Comment by mraross** [comment]
foundCount := 0
loop until foundCount = pointCount
   pick a site at random 
   if site location within bbox and site locality is in list of localities then
      add site to results
      increment foundCount
  endif
endloop
return results

**Comment by cmhodgson** [comment]
90% of the localities that have any sites in them at all have less than 2500 sites. If you ask me for a random site in a locality that contains 1/1000 of the sites in the province, using your algorithm I expect to randomly select 1000 sites before I find 1 in the right locality. You might ask me for 10 or 100 sites. You might ask me for more sites than there are in the locality, or there may be no sites in the locality at all. We will need at least a little bit of structure to provide random points in specific localities. It might require another 20-50MB of memory to store a list of sites in each locality. It's not a lot, but I just wonder if it is really needed.

Also, I assume we don't want duplicate sites returned?

**Comment by mraross** [comment]
Can't we just pick a site at random and reject until we get enough? If not, we just drop the locality requirement and stick with bbox.

**Comment by cmhodgson** [comment]
We can try it and see. I think we will at least need to guard against asking for tiny localities and localities with no sites.

**Comment by cmhodgson** [comment]
Oh I didn't think about the bbox requirement.... that has a similar problem but we can give it a try and see. For small bboxes we can get all the sites and pick from them, and for large bboxes the repeated random draws should work ... but the difference between a smallish box in Vancouver and even a larger one in northern BC may cause some issues.

**Comment by mraross** [comment]
There are two ways to sample:
generate a point and test if its valid
find all sites within bbox and choose one at random
We will leave it as a feasibility task to determine which approach is best.

**Comment by mraross** [comment]
So here is the latest proposal: take random sample points from the bbox and find the nearest site

```
if bbox contains no sites then
   return empty results
endif

if bbox contains less than maxResults then
    maxResults := number of sites in bbox
endif 

resultCount := 0
loop while resultCount < maxResults
        randomPoint := pick a point at random within bbox
        randomSite := sites/nearest?point=randomPoint
        Add randomSite to results
endloop
return results

**Comment by cmhodgson** [comment]
How do we handle duplicates? Find the next-nearest tot he sample-point? Or just drop them and keep sampling? This could affect the balance of samples from sparsely populated areas vs heavily populated.

**Comment by mraross** [comment]
There is a flag called withReplacement that sets the replacement policy. If not set to true, you just check that the site isn't already in the results before adding. We adjust maxResults before going into the loop to account for bbox's with less than maxResults.

**Comment by cmhodgson** [comment]
Fair enough. Why would we even go into the sampling loop if there are fewer sites in the box than you are asking for, don't we just return them all? Also, figuring out how many sites are in the BBox isn't a trivial operation for large bboxes... as long as we are ok with 10 sec+ response times for large bboxes then we are probably ok.

**Comment by mraross** [comment]
Good point. If withReplacement=false, you can just use everything in the bbox. If you do allow replacement, you need to sample.

I think 10 - 20 second response time is ok. Any more is a problem.

**Comment by mraross** [comment]
Not needed at this time
