### ISSUE TITLE
in route planner, add a roadVoronoi resource

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#160]
roadVoronoi takes a set of points and returns a list of (blockID, pointID) pairs, one pair for each block in DRA. This basically precomputes the nearest point to a given block for every block in DRA. 

In address prep, run roadVoronoi for each occupant type (as determined by some tagging convention), and store the results

**Comment by cmhodgson** [comment]
This service will use the same back-end functionality as the service area pre-processing.

**Comment by mraross** [comment]
Issue moved to [bcgov/ols-router #45](https://github.com/bcgov/ols-router/issues/45) via [**ZenHub**](https://www.zenhub.com/)
