### ISSUE TITLE
Analyse rejected addresses looking for error patterns that can be automatically corrected

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#163]

**Comment by mraross** [comment]
Please update estimate with effort remaining.

**Comment by gleeming** [comment]
This was just a general placeholder for salvage analysis.  At this point all of the initial hours we allocated (40) have been used up.  Further work has been put on hold, though a means to operationalize highway recovery still needs to occur.

**Comment by gleeming** [comment]
Here's a summary of what was accomplished in the initial review phase:
- acquired and translated a variety of data sources into GIS-compatible input files
- set up an ArcGIS environment and created theming layers
- reviewed attribute commonalities and visual clusters in rejected/failed data records
- concluded that the many street type & direction missing/different fault cases were too variable for any reasonable salvage approach
- prototyped and tested an FME salvage script to correct data inconsistencies which contain two Hwy words

**Comment by mraross** [comment]
Verified.
