### ISSUE TITLE
in geocoder, add a resource that represents the service area for a given occupant and occupant type

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#165]
/geocoder/occupants/serviceAreas/{serviceType}/{serviceCentreId} 

will return all of the occupant properties as well as the additional service centre properties. Where the {serviceType} is specified by the tag used in GSR to identify the type of service offered by the centre.

     - service area population estimate
     - service centre location point (as part of occupant details)
     - total distance of population to service centre
     - total road network length

Service area population estimates are aggregation of DRA block population estimates which can be sourced from StatsCan under an OGL license.

The type parameter will be used in a tag search for an internally created and managed type tag (e.g., occupantType:firehall)

Internally make ServiceCentre a subclass of occupant with the additional service centre (area) properties.

**Comment by mraross** [comment]
All service area properties should be statically computed during offline data prep.

**Comment by cmhodgson** [comment]
dependent on #193

**Comment by mraross** [comment]
Issue moved to [bcgov/ols-geocoder #55](https://github.com/bcgov/ols-geocoder/issues/55) via [**ZenHub**](https://www.zenhub.com/)
