### ISSUE TITLE
in geocoder, add a resource that represents all services areas for occupants of a given type

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#166]
occupants/serviceAreas?&type=

returns a list of service areas associated with given tag; each service area is represented by its resource URL
The type parameter will be used in a tag search for an internally created and managed type tag (e.g., occupantType:firehall)

**Comment by mraross** [comment]
All serviceAreas are statically computed offline during data prep

**Comment by cmhodgson** [comment]
How are the service areas calculated? Using some off-line router prep code similar in practice to the way the rangebuilder works for the geocoder? Are the service areas a polygonal coverage of the entire province, using the driven-distance voronoi algorithm? We still need to develop a way to polygonize the segment-based coverage, it will have a lot of points in it (same resolution as the roads) probably not appropriate for eg. a web-map of the province. How would people use this service? Is it really more of a fixed download for a given tag?

**Comment by mraross** [comment]
I propose they be calculated with the graph voronoi algorithm.
It is a fixed download of a precomputed polygon. It only needs one point per intersected road segment.
Once downloaded it can be displayed on a map or used for analysis.

**Comment by mraross** [comment]
Perhaps we should have a bbox parameter  and restrict its area to a value that doesn't generate too much data.

**Comment by mraross** [comment]
We could distribute all service areas as file downloads in the BC Data Catalogue since they are statically computed; there could be one file for each service centre type (e.g., schools), format, and projection (maybe just 4326 and 3005).

**Comment by mraross** [comment]
Will be handled by loading generated services area into warehouse for access by WMS and WFS
