### ISSUE TITLE
Extend location services admin app to support router configuration

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#169]
Also need to change where router gets its configuration data from
Change app name from geocoder admin to location services admin

**Comment by cmhodgson** [comment]
add Config params for router:
maxPairCount = ? (pairCount = fromPoints x min(toPoints, topRouteRoute)
maxRoutePoints = ?
implement these restrictions in router.

**Comment by cmhodgson** [comment]
This is done and working in delivery now.

**Comment by mraross** [comment]
Verified in test
