### ISSUE TITLE
In geocoder/addresses resources, add a brief parameter that reduces result attributes to a minimum

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#171]
geocoder/addresses resources returns thirty-two attributes for each matching site. This can be reduced to leaving out individual address elements and seldom-used metadata fields. 

Add a brief parameter to control the level of attribution for each matched address. If brief=true, the following parameters are returned:

fullAddress, accessNotes, locationDescriptor, locationAccuracy, score, matchPrecision, precisionPoints, faults, siteId, siteStatus, blockId

If brief=false all parameters are returned

Default value of brief=false for backwards compatibility

**Comment by cmhodgson** [comment]
I have implemented the brief parameter for all output formats except shp, csv and gml. In the process I "harmonized" the JSON and HTML output to allow the mechanism that handles deciding "what" to output to be shared, while the individual JSON/HTML output just deal with the "how". My intent was to carry this on to the other formats but it was more complicated than I hoped and so I just sprinkled "if(isBrief())" throughout the KML output code.

SHP and CSV both require separate schemas to be defined for the "brief" output, and GML I just don't think anyone is going to use. We can do the support for these as well but I feel the priority is lower.

**Comment by cmhodgson** [comment]
The comment above applies to #172 and #180 as well.

**Comment by cmhodgson** [comment]
We agreed that brief parameter would only apply to the (geo)json, (x)html, and kml outputs.

**Comment by mraross** [comment]
The following properties not coming out in brief output:
locationDescriptor, locationAccuracy, siteId, siteStatus, blockId

**Comment by cmhodgson** [comment]
If you can provide me a URL showing those fields missing, then please do. It actually looks to me like all fields are always present and the brief parameter does nothing at all, right now.

**Comment by mraross** [comment]
https://delivery.apps.gov.bc.ca/pub/geocoder/addresses.json?echo=false&brief=true&addressString=10+Bushby+St%2C+Victoria%2C+BC

**Comment by mraross** [comment]
I see. The api request response is correct. Its just the location services demo app that isn't displaying these fields.

**Comment by cmhodgson** [comment]
The location services app was never requested to have it's output changed, it never output these fields before. The idea was to not transfer the fields it wasn't showing, but then you requested that the brief output include a bunch of additional fields.

It is 99% implemented, I just neglected to pass the brief parameter through at one stage (apparently). I'm not sure why you created a new ticket #172 instead of just reassigning this ticket back to me?

**Comment by cmhodgson** [comment]
Sorry I forgot we had several tickets for this one feature (I know it spans multiple requests but it is really just one feature).

**Comment by mraross** [comment]
OK, back to you.

**Comment by cmhodgson** [comment]
Fixed in Delivery now.
