### ISSUE TITLE
In geocoder/sites resources, add a brief parameter that returns min number of attributes

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#172]
geocoder/sites resources returns thirty-two attributes for each matching site. This can be reduced to leaving out individual address elements and seldom-used metadata fields.

Add a brief parameter to control the level of attribution for each matched address. If brief=true, the following parameters are returned:

fullAddress, accessNotes, locationDescriptor, locationAccuracy, siteId, siteStatus, blockId

If brief=false all parameters are returned

**Comment by cmhodgson** [comment]
We agreed that brief parameter would only apply to the (geo)json, (x)html, and kml outputs.

**Comment by mraross** [comment]
When brief=true, all attributes are still being returned. See
https://delivery.apps.gov.bc.ca/pub/geocoder/addresses.json?echo=false&brief=true&addressString=10+Bushby+St%2C+Victoria%2C+BC

**Comment by mraross** [comment]
Verified in delivery
