### ISSUE TITLE
Add location of first intersection to each leg of route directions

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#174]
For an example, see [mapquest](https://www.mapquest.ca/directions/list/1/ca/bc/victoria/to/ca/bc/atlin?unit=k)

The intersection id and location can be used in routing applications to zoom the map to the first intersection in the leg.

Submitted on behalf of Peter Spry, MOTI:

'Could you return the directions in a way that would allow the individual directions to be linked to the vertices or line segments of the route? That way it would be possible to show where on the map a particular turn was.'

**Comment by cmhodgson** [comment]
Should consider the most useful way to represent this... in JSON I guess a geojson point within each direction would be best.

**Comment by cmhodgson** [comment]
This is implemented and working in delivery. In JSON the directions are now an array of objects, each with a point and text value.
