### ISSUE TITLE
In geocoder/addresses, improve the way partial names are handled

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#176]
There are two problems with geocoder/addresses in its interaction with the name autocompletion tools:
single words aren't autocompleted, and single-word street name aliases are different than their official streetName which leads to confusion. 

For example, in the location services demo address tab, if you enter Black, you get:
```
Black Bridge, Kennedy Lake, BC
Black Creek Bridge, Black Creek, BC
Black Lane, Tofino, BC
Black Rd, Black Creek, BC
```
instead of
```
Black Bear TR 17 Bridge, BC
Black Creek Bridge, Black Creek, BC
Black Bear Lane, Tofino, BC
Black Creek Rd, Black Creek, BC
```
It was agreed that handling partial name matches in the parser is better than the current method of generating partial street and locality name aliases. In the past, handling partial name matches in the parser was ruled out because all the street centroids would have to be loaded which would be more trouble than it was worth. Handling partial name matches in the parser makes address prep simpler because pseudo-aliases and centroids for pseudo-street aliases don't have to be generated.

**Comment by mraross** [comment]
Try the following url:

    https://delivery.apps.gov.bc.ca/pub/geocoder/addresses.kml?addressString=black%20rd&maxResults=5

The first result will be Black Rd, Black Creek, BC but the road is actually called Black Creek Rd and all sites on this road have the correct streetName.


The second result will be Black Rd, Fort Fraser, BC but the road is actually called Black Bear Loop Rd. Again, all sites on the road have the correct streetName.

The third result will be Black Rd, Powell River, BC but the road is actually called Black Point Rd and all sites on this road have the correct streetName

The fourth result will be Black Rd, Sechelt, BC but the road is actually called Schetxwen Rd and all sites on this road have the correct streetName


The fifth result will be Black Rd, Squamish, BC but the road is actually called Black Bear Rd and all sites on this road have the correct streetName


Also try this
    https://delivery.apps.gov.bc.ca/pub/geocoder/addresses.kml?addressString=red&maxResults=5

which returns Red, Indian Arm, BC which looks similar to a previous issue. 

salmon  returns salmon bridge, falklands but there is no salmon bridge, falklands, just a holmes bridge falklands that the salmon bridge match is located at

**Comment by mraross** [comment]
blah

**Comment by mraross** [comment]
You could add an autocomplete flag to inform the parser that addressString is a partial address and to take appropriate action, like performing a prefix search on a name dictionary.

**Comment by cmhodgson** [comment]
If autocomplete == true:
bla => Black Creek, Black Bear, Black Bear Loop, Black Point
sea => Sea, Sea Island 3, Seascape
ced => Cedar, Cedar Hill, Cedar Hill Cross
bro => Broad, Broadway
hill => Hillside, Hillcrest
cedar hi => cedar hill cross

If autocomplete == false:
bla => <none>
black => Black Creek, Black Bear, Black Bear Loop, Black Point
sea => Sea, Sea Island 3
ced => <none>
cedar => Cedar, Cedar Hill, Cedar Hill Cross
bro => <none>
hill => <none>
cedar hi => <none>

Method: if autocomplete && it is the last word, allow any prefix match (possibly subject to some kind of limit (maxResults?)) to prevent excessive matches. If not in autocomplete, for any word, allow word-based prefix matching (the suffix starts with a space character).

**Comment by mraross** [comment]
Testing on dev platform at Refractions:

Odd
-------
Black => Black Creek, BC twice in the top five choices

Good
---------
Bla => Black Creek, BC in the top five choices
Blac => Black Creek, BC in the top five choices

Great
------
One Hun => 100 Mile House, BC
Hun => 100 Mile House, BC

**Comment by cmhodgson** [comment]
To answer for the oddity, there are 2 black creeks in BC... it is showing you both... but you have no way to differentiate them so I agree that it is less than ideal from a UI standpoint... There are about 70 localities with duplicate names, 4 of which are apparently in triplicate: Dog Creek, Pine Valley, Shuswap, Summit Lake. Try typing "dog" ...

**Comment by cmhodgson** [comment]
I just realized that I am not stripping out the extra aliases created in the pre-processing for the multi-word handling for localities (I am doing so for the street names though) So this might be making the problem even worse, I will fix this tomorrow (Tuesday).

**Comment by cmhodgson** [comment]
So stripping out the multi-word locality aliases is not really do-able without reprocessing using new code that doesn't create them in the first place. Upon closer inspection they should not be affecting the results in these cases anyway.

**Comment by mraross** [comment]
I don't think we need to change the API to handle multiple localities with the same name. We could change the demo app to always return and display the top N matches  ( where N is the number of choices in the address pick list) with the chosen address first and selected in a list in the side panel and zoomed to in the map. The user can select the other localities from the list to see where they are.

**Comment by cmhodgson** [comment]
So we definitely need some kind of penalty for the multi-word expansion because if you input "beaver point rd" then "beaver point rd" needs to come back as a better match than "beaver point camp access rd".

**Comment by cmhodgson** [comment]
We added STREET_NAME.partialMatch and LOCALITY.partialMatch faults at 1 point which are applied when a multi-word expansion is done. This results in better matching behaviour.

**Comment by mraross** [comment]
confimed in delivery
