### ISSUE TITLE
Add support for new ITN transport line types: runway and trail recreation

### ISSUE THREAD

**Issue by gleeming** [bcgov/api-specs#178]
GeoBC has created two new transport line types for demographic features: runway (RR) and trail recreation (TR).  They should be added to the enumeration.

Also like other trail types, passenger ferries, virtuals, etc. these are undesirable for pathing purposes and should not be edge candidates for the network.  Analogous changes were made in ticket #43.

**Comment by cmhodgson** [comment]
Done. No special handling is needed in the geocoder for non-routeable classes.

**Comment by gleeming** [comment]
Examples in the June data:
Embleton Mountain Trail, Heffley Lake, BC
CAM3 Runway 13-31, Duncan, BC

**Comment by mraross** [comment]
Verified in delivery
