### ISSUE TITLE
Match scores are incorrectly going below zero

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#18]
A score of -33 is returned from "BOX 939, Garbage, BC"

I've also seen a -5 score for a street precision match with the following faults: [UNRECOGNIZED.notAllowed:33, LOCALITY.notMatched:35, STREET_TYPE.notMatched:3, STREET_QUALIFIER.notMatched:1, STREET_QUALIFIER.spelledWrong:1, CIVIC_NUMBER.notInAnyBlock:10]. This was observed when playing around in a subset of data used for testing. Unfortunately I haven't been able to cook up a similar case against the full data.

When penalty points are so severe that the score is less than one, we probably just want to use our fall-back address instead.

**Comment by cmhodgson** [comment]
Test Url: http://delivery.apps.gov.bc.ca/pub/geocoder/addresses.html?addressString=BOX%20939,%20Garbage,%20BC

**Comment by mraross** [comment]
Verified in delivery

**Comment by mraross** [comment]
verified in test
