### ISSUE TITLE
In occupants/addresses resources, add a brief parameter that returns min number of attributes

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#180]
geocoder/occupants/addresses resources can return up to thirty-two attributes for each matching address. This can be reduced by leaving out individual address elements and seldom-used metadata fields.

Add a brief parameter to control the level of attribution for each matched address. 

If an occupant match is found and brief=true then
   return occupant properties plus fullAddress, accessNotes, locationDescriptor, locationAccuracy, score, matchPrecision, recisionPoints, faults, siteId, siteStatus, blockId

If an occupant match is not found and brief=true then
   return fullAddress, accessNotes, locationDescriptor, locationAccuracy, score, matchPrecision, 
              precisionPoints, faults, siteId, siteStatus, blockId

if brief=false then return all properties

Default value of brief=false for backwards compatibility

**Comment by cmhodgson** [comment]
This will piggy-back onto #172

**Comment by cmhodgson** [comment]
We agreed that brief parameter would only apply to the (geo)json, (x)html, and kml outputs.

**Comment by mraross** [comment]
Verified in delivery
