### ISSUE TITLE
Add a geocoder resource that returns the location of the nearest road point to a given point and its associated block id

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#182]
geocoder/roads/nearest take a point parameter and returns the nearest point on a road segment to the given point. Its also returns the id of the road segment the road point is contained in.

**Comment by pspry** [comment]
Could this request also project the point onto the road segment and return that coordinate?

**Comment by mraross** [comment]
Can do.

**Comment by cmhodgson** [comment]
To be consistent with other naming such as "streetName", should this resource be located at /geocoder/streets/nearest? Futhermore, we are not returning the street itself (compare sites/nearest, intersections/nearest), we are returning some information about the street (perhaps only the blockid?) and also the nearest point on the street to the given point. Imagine if we wanted to implement /geocoder/streets/within in order to put clickable street segments on the map, these streets would have the full segment geometry, not just a point. Perhaps it should even be /geocoder/streetSegments/nearestLocation? And we return a "streetLocation" object, with a blockId and point geometry? What formats do we need to support for this request? HTML, JSON, KML? I'd love to not support XML/GML, going forward, and shp and csv may not be necessary for this request?

**Comment by cmhodgson** [comment]
Lets call it: /geocoder/blocks/nearestPoint
which returns a "pointOnBlock" with  blockId and Point, and locationDescriptor
It has a LocationDescriptor Parameter which accepts "routingPoint" exactly on line or "blockFacePoint" offset to the correct side of the line by an admin-configurable amount called "blockFaceOffset" - defaults to 0.5m. We will start with support for HTML, JSON, KML.

**Comment by pspry** [comment]
JSON/GeoJSON work for me as typical use will be from browser client.

**Comment by cmhodgson** [comment]
What should the default locationDescriptor be?

**Comment by mraross** [comment]
accessPoint

**Comment by cmhodgson** [comment]
The choices are: "routingPoint", "blockFacePoint" - unless you want to define what "accessPoint" means in this context.

**Comment by mraross** [comment]
Let me think about that.

**Comment by cmhodgson** [comment]
I guess that accessPoint could be defined like blockFacePoint, except with an offset equal to the road width? It would be consistent with other access points in terms of relative location, even if the meaning of "access" is a bit twisted

**Comment by cmhodgson** [comment]
After a short discussion we decided that blockFacePoint will be the default.

**Comment by mraross** [comment]
On further reflection how about replacing locationDescriptor parameter with an offset parameter which is a distance in metres. So, the resource always returns a routingPoint with a variable offset that clients can use to ensure the point is on the correct side of the road and closer to the correct road than any other road. The default offset should be 0.5 metres.

**Comment by pspry** [comment]
Offset being the distance between the input point and the returned point on the ITN?

**Comment by mraross** [comment]
No, offset is an input parameter that specifies how much to one side the routingPoint should be offset from the centreline.

**Comment by pspry** [comment]
I would expect the routingPoint would return "the location of the nearest road point", not a point that is near the road. The offset direction, and hence, correct side of the road, can be determined by comparing the location of the input point with the submitted point. I envision this service as projecting a point **onto** the center line, so I'm not keen on the idea of moving the projected point **off** of the center line.

**Comment by pspry** [comment]
That works, and it would work in a similar manner to the "setBack" parameter of the Address GeoCoder. Thanks.

**Comment by mraross** [comment]
Great. Maybe we should rename offset, setBack to be consistent with the rest of the geocoder.

**Comment by cmhodgson** [comment]
I have already implemented this assuming that the locationDescriptor and setBack parameters would work as they do for site points:
- if locationDescriptor = RoutingPoint, setBack is ignored, a point on the centreline is returned
- if locationDescriptor = AccessPoint, the curb Offset is calculated based on the width of the road class, and the setBack is added to that offset to determine the location of the final point
- if locationDescriptor = blockFacePoint (this is brand a brand new locationDescriptor) my intent was to ignore the setBack, and offset the point from the line by the amount specified by the internal admin parameter, which would be set to 0.5 and not be user-configurable

The intent of the blockFacePoint locationDescriptor was to allow the result of this call to be passed as input to the router, requiring the point be closer to the identified segment than to any other, while still be on the correct side, so the router could do side-based routing (taking into account the direction of travel on the given side of the street as the initial or final direction of the route). The router does not yet do this side-based routing but we thought it would be important.

AccessPoint is the default locationDescriptor returned for sites but I don't feel it is wrong to make RoutingPoint the default for this resource.

**Comment by mraross** [comment]
That works too.

**Comment by mraross** [comment]
Maybe this resource should be in the router, not the geocoder?

**Comment by pspry** [comment]
That is a valid question. I see it being used always in conjunction with the router.

**Comment by mraross** [comment]
Would it save a spatial index in the geocoder?

**Comment by mraross** [comment]
PSPRY: Requesting a route with start and end point set to your source point will return a route with start and end points set to the snap point so there is no need for a new router resource

**Comment by mraross** [comment]
This was undertaken under geocoder enhancements

**Comment by pspry** [comment]
Awesome!

**Comment by mraross** [comment]
PSPRY: If you have two points near a road segment, you can make a router.api.gov.bc.ca/route request and the points will be snapped to the road segment and the geometry of that portion of the segment will be returned.

**Comment by mraross** [comment]
Existing functional provides functionality of proposed enhancement
