### ISSUE TITLE
Revise handling of street segments with unknown RoadClass values 

### ISSUE THREAD

**Issue by cmhodgson** [bcgov/api-specs#183]
Instead of dropping segments with unknown RoadClass values during the data processing, they will be logged by the processing and allowed through to the data files, where geocoder will treat them as an "unknown" RoadClass. This class will have its own width values for curb location calculation, defaulting to the same as the "local" RoadClass.

**Comment by mraross** [comment]
Unknown road class should also be drivable like the local RoadClass

**Comment by cmhodgson** [comment]
This is done. Drivability has no effect on the geocoder's function, that is a router concern.

**Comment by cmhodgson** [comment]
Pretty sure this is under the wrong milestone, moving to 3.2.

**Comment by mraross** [comment]
Verified in prod
