### ISSUE TITLE
 Widen field type for EXECUTIONT in shapefile output

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#19]
Currently EXECUTIONT is set as a number(7,3) in the DBF file of the shpz output format for a geocode. This only leaves space for properly reporting a max of 3 digits to the left of the decimal. For computation times exceeding a second, the value gets set to 9999999.

Not sure if this affects any other formats and resources, but at least for shapefiles this should be changed to at least number(9,3).

A slow-running test example is: UNIT 30 -- 2720 Mill Bay Rd, Mill Bay, BC

**Comment by BK01** [comment]
Verified as resolved in Geocoder TEST environment using provided example at executionTime = 2690.927
