### ISSUE TITLE
Assess the extent of missing navigation data in DRA needed to support more accurate routes and travel times in route planner

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#196]

**Comment by cmhodgson** [comment]
Graeme maybe you should estimate this one.

**Comment by gleeming** [comment]
It is a wide open ticket, so I suggest we start with an initial analysis, maybe timebox the following at a day:
- contact GeoBC to get their opinion on the state of nav data and upcoming improvements (e.g from MoT contributions)
- create a layer of candidate intersections (e.g. bi-directional crossings above a certain speed limit with no impactor/restrictions; 4-ways near a light that may represent turn off/on lanes that could illegally skirt the intersection)
- do a general overview (stats, visually) of the above layer to determine the possible extent of deficiencies in rural and urban areas
- use the current route planner to create paths through/around some of the candidates; review these to get a better understanding of the effects and severity

This analysis will only give us anecdotal evidence of the extent of problems in areas we are familiar with on the ground.  It will be difficult to conclude much other than general statistics in the rest of the province, unless a more time consuming review of random routes was performed (e.g. by visually checking them against, say, Google Street View, or against the same routes output from Google).

If followup work is required to get a better assessment, that will have to be estimated separately once we know what to focus on.

**Comment by mraross** [comment]
Issue moved to [bcgov/ols-router #47](https://github.com/bcgov/ols-router/issues/47) via [**ZenHub**](https://www.zenhub.com/)
