### ISSUE TITLE
in geocoder/addresses, provinceCode parameter being ignored

### ISSUE THREAD

**Issue by pramsey** [bcgov/api-specs#2]
The example on the dev guide actually displays this problem:

http://apps.gov.bc.ca/pub/geocoder/addresses.geojson?civicNumber=525&streetName=superior&streetType=st&localityName=victoria&provinceCode=BC

The response notes that there is a fault in the query:

```
{"element":"PROVINCE","fault":"missing","penalty":1}
```

If you use `province` instead, the fault goes away. So a problem in the code or in the documentation. Probably the code, since the return JSON slot for the province is `provinceCode` it would be nice if the query API accepted that slot, as it does for all the other ones.

http://apps.gov.bc.ca/pub/geocoder/addresses.geojson?civicNumber=525&streetName=superior&streetType=st&localityName=victoria&province=BC

**Comment by mraross** [comment]
Thanks for this one too. Its been logged into geocoder tracker. We propose to add support for provinceCode and keep province parameter for backward compatibility

**Comment by mraross** [comment]
Verified

**Comment by mraross** [comment]
verified in test
