### ISSUE TITLE
incorrect postal element fault for an occupant containing a postal element name

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#203]
STN 309 ANAHIM LAKE -- 6637 Marten Rd, Anahim Lake, BC

returns the following faults:
 POSTAL_ADDRESS_ELEMENT.notAllowed	
 OCCUPANT_NAME.partialMatch

The STN in the occupant name is being treated incorrectly as a postal element name.

**Comment by cmhodgson** [comment]
Alter the postal element regexs to check for the frontgate, stuff to the left of the front gate doesn't get flagged

**Comment by mraross** [comment]
Is this implemented?

**Comment by cmhodgson** [comment]
It has not been assigned a release, or moved into backlog, so no, I didn't know this was to be done.

**Comment by mraross** [comment]
That's fine. Please provide an estimate.

**Comment by cmhodgson** [comment]
Already provided .

**Comment by mraross** [comment]
Do we have enough time left for this?

**Comment by cmhodgson** [comment]
Sure. Does this apply to all "postal junk"? eg. what if there is a postal code before the front gate? POBOX, RURAL ROUTE, GENERAL DELIVERY?

**Comment by mraross** [comment]
Yes it does. Good catch.

**Comment by cmhodgson** [comment]
Done in delivery now.

**Comment by mraross** [comment]
All postal elements except postal code itself are no longer flagged.
Verified in delivery.
