### ISSUE TITLE
Add optimal-route and optimal-directions resources to support optimizing order of route stops 

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#208]
optimal-route is like route but reorders route stops to minimize route length (distance or time). Max number of route point allowed is a configuration parm that can be set with the location services admin app.
Implement using jsprit.

optimal-directions is like optimal-route only directions are returned as well plus the optimal sequence of stop points (e.g., [3 1 2 0] means in the optimal route, visit point 3 followed by point 1, then point 2, then point 0)

**Comment by cmhodgson** [comment]
Some example jsprit code loading a cost matrix and running a VRP: https://github.com/graphhopper/jsprit/blob/master/jsprit-examples/src/main/java/com/graphhopper/jsprit/examples/CostMatrixExample.java

**Comment by mraross** [comment]
optimal-route should take a distance matrix as an input so that this matrix can be created by other routing api's such as google maps.

**Comment by cmhodgson** [comment]
Done and working in delivery now.

**Comment by mraross** [comment]
Verified in test
