### ISSUE TITLE
Create a process to salvage Hwy Hwy and Highway Hwy cases in AddressBC data

### ISSUE THREAD

**Issue by gleeming** [bcgov/api-specs#209]
Until these double highway names are fixed in the source data, we can recover the probable highway number based on address point proximity to ITN highway route segments.  An example is "840 HIGHWAY HWY Kaledon BC" which is close to a Hwy 3A feature in ITN and could be renamed to 840 HWY 3A.

It may be easiest to manually create a static route layer to act as the spatial match source.  Highways don't change much so this should suffice.  The alternative is to set up a dynamic link to the current ITN data, but this would add a lot of likely unnecessary processing to the FME batch prep script.  Once the preferred approach has been discussed and agreed upon, an estimate for completing this work can be made.

Needed by all clients to have as large a reference address list as possible in the geocoder.

**Comment by mraross** [comment]
Issue moved to [bcgov/ols-geocoder #40](https://github.com/bcgov/ols-geocoder/issues/40) via [**ZenHub**](https://www.zenhub.com/)
