### ISSUE TITLE
"Trans-Canada Hwy" cannot be matched from the input "Transcanada Hwy"

### ISSUE THREAD

**Issue by cmhodgson** [bcgov/api-specs#213]
GSR includes the address "#207-5462 transcanada hwy duncan bc" which will not match to the official name of "Trans-Canada Hwy" because internally the "-" is treated as a space. "Trans Canada Hwy" would work. A similar problem exists with compound words, eg. "Hillcrest" vs. "Hill Crest" or "Searidge" vs. "Sea Ridge". Previously these cases were handled by aliases generated in the processing, which has no been removed in favor of run-time handling of multi-word matching, but the current implementation doesn't handle this case. It may be possible to add the compounded words to the dictionary, effectively spell-correcting from "transcanada" to "trans canada" however some work will need to be done to handle the fact that the number of words has changed as this is not currently allowed for.

The reverse case, where the official street name is a compound word eg. "hillcrest" and the input is given as multiple words eg. "hill crest", is even harder to handle. Users entering the name into an auto-complete field will potentially get some help with these cases.

Needed by all clients to reduce the number of missed matches by the geocoder.

**Comment by mraross** [comment]
redundant issue
