### ISSUE TITLE
Add support for a DataBC address source file

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#215]
Add a script that takes a databc_addresses.csv source file and adds it to the set of reference addresses to be further processed.

The schema of the databc_addresses.csv file will include individual address elements, associated metadata, and location specified by lat and lon fields. 

This file will be used by DataBC to manually maintain a list of additional addresses to be integrated into the geocoder. The source of these addresses will be as follows:

1. Corrected addresses salvaged from the rejected files of previous address data prep runs.

2. Addresses supplied ad hoc by external agencies (e.g., by phone or email) that are known by them to be correct and are consistent with current address and road data. 

When integrating addresses, DataBC addresses should have the lowest priority.

**Comment by cmhodgson** [comment]
Re-use hybrid_post input format, add source notes field, lowest priority for site reconciliation
switch to lat/lon input fields for both site and access point inputs
Will require full data prep cycle to fully test

**Comment by mraross** [comment]
Field   Name | Data Type | Description | Required for CAP | Required for NCAP
-- | -- | -- | -- | --
DATABC_ID | number(8,0) | ID used by DataBC; this will be retained internally as the geocoder   YourID | yes | yes
SITE_NAME | char(240) |   |   | yes
UNIT_DESIGNATOR | char(10) |   |   | N/A
UNIT_PREFIX | char(1) | a list of  comma-separated alphabet characters, or   ranges (e.g., A-D). Each character represents a building name. | N/A
UNIT_NUMBER | char(50) | multiple unit numbers and ranges allowed (e.g., 100-112,114-129, 200-219) |   | N/A
UNIT_NUMBER_SUFFIX | char(3) |   |   | N/A
CIVIC_NUMBER | number(6,0) |   | yes | N/A
CIVIC_NUMBER_SUFFIX | char(3) |   |   | N/A
STREET_NAME | char(50) | Full street name including directionals, types and descriptors | yes |  
LOCALITY | char(50) |   | yes | yes
LOCATION_DESCRIPTOR | char(20) | parcelPoint, frontDoor, etc | yes | yes
SITE_POSITIONAL_ACCURACY | char(6) | low, medium or high | yes | yes
SITE_LATITUDE | number(13,9) |   | yes | yes
SITE_LONGITUDE | number(13,9) |   | yes | yes
AP_POSITIONAL_ACCURACY | char(6) | only used for custom AP locations (low, medium or high) |   |  
AP_LATITUDE | number(13,9) | only used for custom AP locations |   |  
AP_LONGITUDE | number(13,9) | only used for custom AP locations |   |  
AP_TYPE | char(4) | CAP or NCAP | yes | yes
IS_PRIMARY_IND | char(1) | Y or N | yes | yes
NARRATIVE_LOCATION | char(240) |   |   |  
PSEUDO_SITE | char(1) | Y or N [a pseudo site will only be used for generating address ranges   from CAPs] | yes | yes [set to N]
superFullSiteDescriptor | char(240) | See ticket #146, e.g. Patient Care Centre--Royal Miracle Hospital |   |  
SOURCE_NOTES | char(240) | DataBC custom comments |   |

**Comment by gleeming** [comment]
I'm increasing the UNIT_PREFIX field width to char(20) because it needs to support a list of ranges

**Comment by gleeming** [comment]
Added support for this file, however there were no records in it as part of the v3.4 data processing and deployment

**Comment by mraross** [comment]
Suggest changing the STREET_NAME column to STREET since it can hold all attributes related to street, not just street name.

**Comment by gleeming** [comment]
Completed the three field name changes and prepped the new source input to reflect this structure

**Comment by mraross** [comment]
Verified in delivery

**Comment by mraross** [comment]
Verified in test
