### ISSUE TITLE
Add a resource that returns all occupants at a given address

### ISSUE THREAD

**Issue by cmhodgson** [bcgov/api-specs#219]
Presently if you input the following addressString to /occupants/addresses:
unit 207 -- 5462 Trans-Canada Hwy, Duncan, BC

You get a UNIT level match returned for that exact address. However, if you input the following:
WOLF unit 207 -- 5462 Trans-Canada Hwy, Duncan, BC

You get OCCUPANT level matches for the following (among others):
Sun Wolf Earthworks Ltd., UNIT 207 -- 5462 Trans-Canada Hwy, Duncan, BC
Iron Wolf Bridge Bridge and Steel, UNIT 207 -- 5462 Trans-Canada Hwy, Duncan, BC

Given that you are using the /occupants/ API, perhaps it would be preferable to return the occupant(s) at the site/unit/civic number matched, rather than the site/unit/civic number matches, if there are such occupant(s).

This would allow us to answer the question "are there any known occupants at this address", which we cannot answer as it is now.

Currently there is no in-memory link between a site and any occupants of that site, the link goes the other way from occupant to site. But we could easily add this link at the cost of an extra pointer for every site.

**Comment by mraross** [comment]
Is that a cost of one pointer per occupant at a given address?

**Comment by mraross** [comment]
Perhaps occupants at a given address should be a separate resource as in:
occupants/atAddress?addressString="unit 207 - 5462 Trans-Canada Hwy, Duncan, BC"

**Comment by cmhodgson** [comment]
I was thinking that there would be at most one occupant per site, otherwise there would be some sub-site structure missing? So each site would have a pointer to a potential occupant. If a site can potentially have multiple occupants, then we would also need a list object for each site with any occupants, and a pointer to each of the occupants, which would likely double the additional memory requirements to support this.

**Comment by mraross** [comment]
Issue moved to [bcgov/ols-geocoder #47](https://github.com/bcgov/ols-geocoder/issues/47) via [**ZenHub**](https://www.zenhub.com/)
