### ISSUE TITLE
During Site processing, duplicate psuedo-sites should all be dropped

### ISSUE THREAD

**Issue by cmhodgson** [bcgov/api-specs#220]
From sources treated as psuedo-sites (eg. RNF), if there are duplicate addresses at different locations, it may be safer to drop all of the duplicates rather than picking one at random to be passed through. 

In the case of #187, there are two segments from RNF with ranges from 1230-1254 and 1230-1290 (starting from the dead end of the road). Picking the wrong 1230 causes the street to have increasing addresses in two different directions.

**Comment by cmhodgson** [comment]
This is a duplicate of #221.

**Comment by mraross** [comment]
Why is 1230 Merridale Rd, Cobble Hill, BC not at the end of the road (it is slightly west of the end)?

**Comment by cmhodgson** [comment]
This issue should be closed as it is an exact duplicate of #221
