### ISSUE TITLE
Discard all pseudo-site candidates that have repeated addresses

### ISSUE THREAD

**Issue by gleeming** [bcgov/api-specs#221]
There are some inconsistencies in pseudo-site data where a single source provides two (or possibly more) records with identical addresses.  This can occur in AddressBC points or RNF data where consecutive ranges share the same start and end value.

Instead of randomly keeping one of the replicate records or anchor points (the current approach) it probably makes sense to not pollute the address candidates with any of these multiples.  This modification can be made in the batch prep FMI scripts for AddressBC and RNF.

**Comment by cmhodgson** [comment]
In the case of #187, there are two segments from RNF with ranges from 1230-1254 and 1230-1290 (starting from the dead end of the road). Picking the wrong 1230 causes the street to have increasing addresses in two different directions, so we would be better off dropping them all.

**Comment by mraross** [comment]
Understood. Confirmed in delivery

**Comment by cmhodgson** [comment]
Graeme, Michael would like an estimate for this fix.

**Comment by gleeming** [comment]
I suggest we only do this for RNF cases because we are taking the ends of ranges from that data source and using them to define address points.  If there is an inconsistency between two ranges we have low confidence in those particular cases.  In the 2016 data there were only 671 repeats.

However for Address BC, we are processing real site addresses and locations provided from munis and RDs.  A large number of them are not open data as part of the addendum and therefore pseudo sites.  I don't envision replicates in these cases (more specifically choosing one representative) causing issues similar to RNF.  If we toss ABC repeats of pseudo sites, we stand to lose a large number of candidates just because they are not open at this time.  Last processing run, almost 200k sites were part of matching sets and we retained 45k unique selections.

**Comment by cmhodgson** [comment]
Sounds reasonable to me.

**Comment by mraross** [comment]
Were pseudo-sites candidates that have repeated addresses discarded for the RNF cases?
