### ISSUE TITLE
Add apType parameter to reverse geocoding to filter for NCAP/CAP

### ISSUE THREAD

**Issue by cmhodgson** [bcgov/api-specs#222]
In order to support bcgov/ols-devkit#77 picking a random site, it would be helpful for sites/nearest to support a parameter such as apType=CAP to limit the reverse-geocoded AP(s) to only CAPs (and not return any NCAPs). This is simpler than coding the random function to ask for extra sites/APs and then filter them in javascript, and is more reusable for others using the API.

**Comment by mraross** [comment]
Implement civicOnly:Boolean; true if only civic addresses should be included in results; false if non-civic address should be included also

**Comment by mraross** [comment]
Verified. Note that civicOnly was implemented as onlyCivic.
