### ISSUE TITLE
in route planner, route goes off to [0,0] and back for no apparent reason

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#225]
https://routerdlv.api.gov.bc.ca/directions.json?apikey=11dd756f680c47b5aef5093d95543738&criteria=fastest&roundTrip=false&points=-133.7017906%2C59.5663764%2C-116.5130556%2C49.0975

response:
{"routeDescription":"","searchTimestamp":"2017-08-05 17:52:49.509","executionTime":3836,"version":"1.4.0","disclaimer":"http://www2.gov.bc.ca/gov/content/home/disclaimer","privacyStatement":"http://www2.gov.bc.ca/gov/content/home/privacy","copyrightNotice":"Copyright 2015 Province of British Columbia - Open Government License","copyrightLicense":"http://www.data.gov.bc.ca/local/dbc/docs/license/OGL-vbc2.0.pdf","srsCode":4326,"criteria":"fastest","distanceUnit":"km","points":[[-133.70179,59.56638],[-116.51306,49.0975]],"routeFound":true,"distance":50.639,"time":3142,"timeText":"52 minutes 22 seconds","route":[[-133.7022,59.56631],[-133.70233,59.56651],[-133.70255,59.56666],[-133.70325,59.56697],[-133.70356,59.56721],[-133.70365,59.56732],[-133.70357,59.5674],[-133.70312,59.56746],[-133.70274,59.56757],[-133.70318,59.56822],[-133.70323,59.56848],[-133.70308,59.56869],[-133.7028,59.56887],[-133.70234,59.56931],[-133.70217,59.56956],[-133.70216,59.56976],[-133.70225,59.56994],[-133.70293,59.57087],[-133.70172,59.57106],[-133.7016,59.57113],[-133.70156,59.57121],[-133.70346,59.57389],[-133.70411,59.57484],[-133.69336,59.57676],[-133.69138,59.57711],[-133.68107,59.579],[-133.67452,59.58012],[-133.67117,59.58066],[-133.67076,59.58072],[-133.66915,59.58026],[0,0],[-116.62355,49.38402],[-116.62445,49.38404],[-116.62493,49.38411],[-116.62501,49.38415],[-116.62571,49.38433],[-116.62619,49.38449],[-116.62637,49.38457],[-116.62644,49.38462],[-116.62677,49.3848],[-116.62696,49.38494],[-116.62715,49.38513],[-116.62733,49.38525],[-116.62777,49.38544],[-116.62816,49.38554],[-116.62858,49.38559],[-116.62911,49.3856],[-116.6297,49.38567],[-116.63015,49.3857],[-116.63087,49.38571],[-116.63152,49.38574],[-116.63203,49.38574],[-116.63273,49.38585],[-116.63391,49.38598],[-116.63427,49.386],[-116.63466,49.38599],[-116.63471,49.38597],[-116.63535,49.38596],[-116.63551,49.38595],[-116.63577,49.38588],[-116.63623,49.38585],[-116.63668,49.38587],[-116.6373,49.38585],[-116.63763,49.3858],[-116.63809,49.38584],[-116.63824,49.38587],[-116.63933,49.38594],[-116.64007,49.38594],[-116.64054,49.38598],[-116.64094,49.38599],[-116.64113,49.38602],[-116.64195,49.38602],[-116.64265,49.38611],[-116.64274,49.38615],[-116.64301,49.3862],[-116.64351,49.38633],[-116.64378,49.38638],[-116.64427,49.38642],[-116.64437,49.38643],[-116.64506,49.38662],[-116.6456,49.38684],[-116.64584,49.38687],[-116.64627,49.38688],[-116.64726,49.38717],[-116.64783,49.38726],[-116.64815,49.38734],[-116.64878,49.3874],[-116.64905,49.38745],[-116.64958,49.38748],[-116.64993,49.38748],[-116.65063,49.38759],[-116.65093,49.38769],[-116.65188,49.38779],[-116.65243,49.38792],[-116.65306,49.3881],[-116.6532,49.38815],[-116.65341,49.38819],[-116.65381,49.38831],[-116.65392,49.38832],[-116.65397,49.38834],[-116.65536,49.38853],[-116.65765,49.38866],[-116.6581,49.38866],[-116.65841,49.38868],[-116.65846,49.38867],[-116.65991,49.38873],[-116.66039,49.38865],[-116.66053,49.38864],[-116.66093,49.38856],[-116.66143,49.3885],[-116.66195,49.38849],[-116.66217,49.38851],[-116.66278,49.38852],[-116.66311,49.38855],[-116.66373,49.38861],[-116.66435,49.38869],[-116.66444,49.38872],[-116.66469,49.38873],[-116.66549,49.38877],[-116.66609,49.38882],[-116.66618,49.38881],[-116.66676,49.38883],[-116.66729,49.38876],[-116.66804,49.38871],[-116.66808,49.38872],[-116.66863,49.38869],[-116.66885,49.3887],[-116.66972,49.38869],[-116.66991,49.38863],[-116.67018,49.38849],[-116.67062,49.38838],[-116.67116,49.3883],[-116.6712,49.38831],[-116.67193,49.3883],[-116.67206,49.38832],[-116.67215,49.38837],[-116.67234,49.38858],[-116.67239,49.38871],[-116.67247,49.38881],[-116.67256,49.38883],[-116.67292,49.38886],[-116.67349,49.38884],[-116.67414,49.3888],[-116.67453,49.38868],[-116.6752,49.38862],[-116.67564,49.38865],[-116.67591,49.38864],[-116.67626,49.38867],[-116.6764,49.38866],[-116.6773,49.38872],[-116.67865,49.38877],[-116.67997,49.38889],[-116.68037,49.38889],[-116.68062,49.38891],[-116.68092,49.38892],[-116.68256,49.38908],[-116.68292,49.38909],[-116.68303,49.38908],[-116.6835,49.38898],[-116.68398,49.38898],[-116.68428,49.389],[-116.68434,49.389],[-116.68465,49.38903],[-116.68498,49.38904],[-116.68507,49.38903],[-116.68545,49.3889],[-116.68574,49.38883],[-116.68641,49.38879],[-116.68755,49.38859],[-116.68787,49.38848],[-116.68791,49.38848],[-116.68795,49.38846],[-116.68808,49.38843],[-116.68812,49.3884],[-116.68857,49.38825],[-116.6891,49.38821],[-116.68914,49.38819],[-116.68943,49.38816],[-116.68988,49.38804],[-116.6902,49.38799],[-116.69043,49.38792],[-116.69048,49.38792],[-116.69053,49.38789],[-116.69086,49.38784],[-116.69111,49.38782],[-116.69146,49.38772],[-116.69177,49.38751],[-116.69204,49.38738],[-116.69229,49.38728],[-116.69298,49.38711],[-116.69339,49.38709],[-116.69358,49.3871],[-116.69384,49.38709],[-116.69404,49.38707],[-116.69433,49.38702],[-116.69486,49.38698],[-116.69507,49.38694],[-116.69562,49.38687],[-116.69571,49.38685],[-116.69595,49.38673],[-116.696,49.3867],[-116.69623,49.3866],[-116.69677,49.38647],[-116.69711,49.38642],[-116.6979,49.38625],[-116.69797,49.38626],[-116.69818,49.38622],[-116.69877,49.38613],[-116.69909,49.38614],[-116.69993,49.38611],[-116.70049,49.38608],[-116.70055,49.38606],[-116.70089,49.38603],[-116.70139,49.38599],[-116.70169,49.38594],[-116.7027,49.3859],[-116.70333,49.38578],[-116.70361,49.38575],[-116.70438,49.38573],[-116.70482,49.38566],[-116.70528,49.38553],[-116.70584,49.38543],[-116.70684,49.38508],[-116.70708,49.38501],[-116.70726,49.38493],[-116.70782,49.38473],[-116.70862,49.38435],[-116.70884,49.38422],[-116.70895,49.38413],[-116.7091,49.38407],[-116.70972,49.38394],[-116.70992,49.38379],[-116.71012,49.38357],[-116.71047,49.38336],[-116.71073,49.38313],[-116.71088,49.38296],[-116.71098,49.38291],[-116.7114,49.38264],[-116.71158,49.38246],[-116.71162,49.38245],[-116.71191,49.38217],[-116.71195,49.38215],[-116.71234,49.38183],[-116.71253,49.38165],[-116.71256,49.38158],[-116.71271,49.38139],[-116.71298,49.38118],[-116.71317,49.3811],[-116.71339,49.38097],[-116.71365,49.38076],[-116.71398,49.38061],[-116.71401,49.38058],[-116.71421,49.38051],[-116.71481,49.38035],[-116.71505,49.3802],[-116.71523,49.38011],[-116.71546,49.38005],[-116.71577,49.38002],[-116.71625,49.37988],[-116.71657,49.37974],[-116.71697,49.37961],[-116.71702,49.37955],[-116.71701,49.37946],[-116.71697,49.37944],[-116.71683,49.37943],[-116.71669,49.37946],[-116.71644,49.37958],[-116.71629,49.37968],[-116.71617,49.37973],[-116.71578,49.37979],[-116.71522,49.37985],[-116.71491,49.37991],[-116.71464,49.38001],[-116.7145,49.38003],[-116.71446,49.38002],[-116.71442,49.37994],[-116.71447,49.37981],[-116.71475,49.37969],[-116.71533,49.3796],[-116.7156,49.37957],[-116.71584,49.37952],[-116.71598,49.37945],[-116.71638,49.37915],[-116.7166,49.37901],[-116.71674,49.37897],[-116.71752,49.37839],[-116.71757,49.37838],[-116.71765,49.37832],[-116.71781,49.37825],[-116.7181,49.37819],[-116.71838,49.37816],[-116.71888,49.37819],[-116.71923,49.3783],[-116.71974,49.37852],[-116.72065,49.37894],[-116.72091,49.37904],[-116.72113,49.37911],[-116.72127,49.37912],[-116.72163,49.37922],[-116.72228,49.3795],[-116.72245,49.37959],[-116.7229,49.37977],[-116.72365,49.3801],[-116.72398,49.38023],[-116.72414,49.38034],[-116.72444,49.38048],[-116.72481,49.3807],[-116.72495,49.38075],[-116.72516,49.38075],[-116.72516,49.38063],[-116.7251,49.38054],[-116.72477,49.38029],[-116.72438,49.37986],[-116.72416,49.37953],[-116.72369,49.37916],[-116.72364,49.37909],[-116.72353,49.3789],[-116.72345,49.37864],[-116.72316,49.37835],[-116.72308,49.3782],[-116.72291,49.37799],[-116.72279,49.37789],[-116.72261,49.3777],[-116.72257,49.37755],[-116.72257,49.37753],[-116.72263,49.37746],[-116.72279,49.37745],[-116.72287,49.37748],[-116.72338,49.37791],[-116.7239,49.37817],[-116.72421,49.3783],[-116.72463,49.37843],[-116.72477,49.3785],[-116.72495,49.37864],[-116.72528,49.37899],[-116.72572,49.37929],[-116.72585,49.37931],[-116.72623,49.37925],[-116.72638,49.37921],[-116.72607,49.37835],[-116.72603,49.37795],[-116.72607,49.37744],[-116.72622,49.37704],[-116.72644,49.37657],[-116.72664,49.37617],[-116.72812,49.37347],[-116.72827,49.3731],[-116.72831,49.37277],[-116.72829,49.37252],[-116.72822,49.37227],[-116.72754,49.37158],[-116.72724,49.37106],[-116.72718,49.37075],[-116.72713,49.36608],[-116.72714,49.36568],[-116.7273,49.36498],[-116.72735,49.36006],[-116.7272,49.35952],[-116.72716,49.35923],[-116.72729,49.35892],[-116.72808,49.35778],[-116.7286,49.35692],[-116.72886,49.3564],[-116.72895,49.35596],[-116.72887,49.35561],[-116.72862,49.355],[-116.72855,49.35448],[-116.72858,49.35373],[-116.72849,49.35333],[-116.72815,49.35244],[-116.72727,49.35116],[-116.72706,49.35075],[-116.72691,49.35016],[-116.72679,49.34986],[-116.72591,49.34872],[-116.72524,49.34739],[-116.72497,49.34693],[-116.72463,49.34656],[-116.72408,49.34623],[-116.72338,49.34595],[-116.7226,49.34573],[-116.72208,49.34554],[-116.72184,49.34538],[-116.72168,49.34517],[-116.72154,49.34434],[-116.72135,49.34403],[-116.72115,49.34381],[-116.72076,49.34358],[-116.71962,49.34314],[-116.71812,49.34218],[-116.71689,49.34148],[-116.71621,49.34069],[-116.71529,49.34019],[-116.71423,49.33926],[-116.71275,49.33837],[-116.71243,49.33815],[-116.71212,49.33787],[-116.71188,49.33731],[-116.71185,49.33691],[-116.7117,49.3366],[-116.71148,49.33641],[-116.71068,49.33597],[-116.71058,49.33585],[-116.71038,49.33531],[-116.71034,49.33513],[-116.71039,49.33497],[-116.71045,49.33433],[-116.71036,49.33402],[-116.71021,49.33381],[-116.70884,49.33252],[-116.7081,49.33179],[-116.70682,49.3307],[-116.70646,49.33046],[-116.70609,49.3303],[-116.70576,49.33023],[-116.70545,49.33024],[-116.70515,49.33031],[-116.70435,49.33077],[-116.70405,49.33088],[-116.70364,49.33094],[-116.70328,49.33093],[-116.70293,49.33088],[-116.70262,49.33078],[-116.70229,49.33059],[-116.70094,49.32935],[-116.69915,49.32766],[-116.69819,49.32681],[-116.69483,49.32471],[-116.69394,49.32426],[-116.69212,49.32342],[-116.69068,49.32229],[-116.68913,49.32141],[-116.68828,49.32075],[-116.6879,49.32054],[-116.68561,49.31968],[-116.68512,49.31941],[-116.68454,49.31899],[-116.68424,49.31866],[-116.68382,49.318],[-116.68336,49.31759],[-116.68239,49.31712],[-116.68138,49.31649],[-116.68037,49.31571],[-116.6798,49.31517],[-116.67926,49.31443],[-116.67819,49.31371],[-116.67658,49.31283],[-116.6756,49.31253],[-116.67507,49.31228],[-116.67459,49.31201],[-116.67219,49.31027],[-116.67144,49.3096],[-116.67072,49.30884],[-116.66926,49.30777],[-116.66798,49.30688],[-116.66696,49.30591],[-116.66643,49.30551],[-116.6642,49.30408],[-116.66382,49.30379],[-116.66302,49.30298],[-116.66264,49.30249],[-116.66216,49.30178],[-116.6617,49.30039],[-116.66114,49.2999],[-116.65988,49.29918],[-116.65942,49.29882],[-116.65837,49.29761],[-116.65808,49.29709],[-116.65788,49.29603],[-116.65751,49.29553],[-116.65702,49.29499],[-116.65519,49.2931],[-116.65403,49.2922],[-116.65354,49.29173],[-116.65313,49.29123],[-116.65271,49.29057],[-116.65247,49.29005],[-116.65234,49.28934],[-116.65226,49.28816],[-116.65234,49.28744],[-116.65277,49.2865],[-116.65347,49.28581],[-116.65396,49.28509],[-116.65411,49.28437],[-116.65394,49.28353],[-116.65372,49.28291],[-116.65361,49.28262],[-116.6532,49.28132],[-116.65249,49.28043],[-116.65221,49.27993],[-116.65211,49.27962],[-116.65205,49.27924],[-116.65204,49.27811],[-116.65194,49.27783],[-116.65144,49.27695],[-116.65142,49.27651],[-116.6521,49.27534],[-116.65225,49.27501],[-116.65229,49.27465],[-116.65223,49.27438],[-116.65213,49.27414],[-116.65151,49.27339],[-116.65073,49.27283],[-116.65032,49.27248],[-116.64998,49.27197],[-116.64978,49.27042],[-116.64881,49.26789],[-116.64824,49.26715],[-116.64808,49.26685],[-116.648,49.26648],[-116.64809,49.26612],[-116.64823,49.26575],[-116.64828,49.26534],[-116.64804,49.26476],[-116.64738,49.26371],[-116.6462,49.26137],[-116.64567,49.26056],[-116.64528,49.26011],[-116.64475,49.25971],[-116.6437,49.25908],[-116.643,49.25874],[-116.64193,49.25831],[-116.64072,49.25788],[-116.64045,49.25773],[-116.63923,49.25681],[-116.63901,49.25671],[-116.6376,49.2563],[-116.637,49.25618],[-116.6366,49.25605],[-116.63569,49.2556],[-116.6346,49.25499],[-116.63365,49.25471],[-116.63263,49.25452],[-116.63229,49.25438],[-116.6317,49.25399],[-116.63077,49.25352],[-116.63023,49.25334],[-116.62934,49.2531],[-116.62891,49.25293],[-116.62715,49.25198],[-116.62698,49.25184],[-116.62659,49.25078],[-116.62617,49.25039],[-116.62557,49.24954],[-116.62525,49.24887],[-116.62361,49.24647],[-116.62181,49.24441],[-116.61958,49.24159],[-116.61869,49.241],[-116.61719,49.24013],[-116.61693,49.23985],[-116.61664,49.23945],[-116.61432,49.23774],[-116.61319,49.23704],[-116.61226,49.23631],[-116.61133,49.23548],[-116.61122,49.23532],[-116.61111,49.23505],[-116.61111,49.23475],[-116.61098,49.23438],[-116.61059,49.23409],[-116.61018,49.23372],[-116.60997,49.23346],[-116.60928,49.23192],[-116.60918,49.23178],[-116.60851,49.23126],[-116.60729,49.22852],[-116.60691,49.22776],[-116.6063,49.22688],[-116.60552,49.22603],[-116.60442,49.22476],[-116.60351,49.22312],[-116.60299,49.22158],[-116.60172,49.22004],[-116.60113,49.21966],[-116.60092,49.21936],[-116.60065,49.2182],[-116.60061,49.21711],[-116.60034,49.21649],[-116.60002,49.21627],[-116.59955,49.21601],[-116.59829,49.21548],[-116.59678,49.21474],[-116.59646,49.21448],[-116.5963,49.21424],[-116.59625,49.21386],[-116.59624,49.21376],[-116.59626,49.21278],[-116.59624,49.21257],[-116.59608,49.2124],[-116.59497,49.21181],[-116.594,49.21111],[-116.59181,49.20983],[-116.59151,49.20958],[-116.5912,49.20928],[-116.59097,49.20894],[-116.59063,49.20831],[-116.59002,49.20694],[-116.58991,49.20599],[-116.58956,49.20556],[-116.58742,49.20377],[-116.58635,49.20258],[-116.58459,49.20087],[-116.5843,49.20067],[-116.5827,49.19966],[-116.58242,49.1994],[-116.58164,49.19851],[-116.57989,49.19735],[-116.57971,49.19717],[-116.57958,49.19691],[-116.57971,49.19558],[-116.57933,49.19466],[-116.57913,49.19395],[-116.57924,49.19264],[-116.57924,49.19167],[-116.57914,49.1911],[-116.57894,49.19069],[-116.57866,49.19034],[-116.57825,49.19002],[-116.57779,49.18976],[-116.577,49.18945],[-116.57498,49.18876],[-116.5722,49.18802],[-116.5718,49.18786],[-116.57141,49.18762],[-116.56942,49.18583],[-116.56887,49.18543],[-116.56491,49.18323],[-116.56401,49.18281],[-116.56308,49.18243],[-116.56222,49.1822],[-116.56146,49.18208],[-116.55923,49.18203],[-116.55868,49.18195],[-116.5581,49.18177],[-116.5571,49.1813],[-116.55644,49.18106],[-116.55147,49.17972],[-116.55094,49.17946],[-116.55056,49.17914],[-116.54989,49.17854],[-116.54959,49.17834],[-116.54915,49.17816],[-116.54474,49.17708],[-116.54153,49.17667],[-116.54092,49.17656],[-116.5403,49.17629],[-116.53989,49.17596],[-116.53959,49.17553],[-116.53956,49.17514],[-116.53986,49.17228],[-116.54011,49.16664],[-116.54009,49.16476],[-116.53993,49.1642],[-116.53934,49.16272],[-116.53908,49.16177],[-116.53893,49.1606],[-116.53892,49.15977],[-116.53931,49.15719],[-116.53939,49.15527],[-116.5393,49.15483],[-116.53646,49.15029],[-116.5359,49.14945],[-116.53525,49.14882],[-116.5342,49.14772],[-116.5338,49.14705],[-116.53305,49.14515],[-116.53272,49.1428],[-116.53262,49.1424],[-116.53213,49.14129],[-116.52979,49.13646],[-116.5289,49.13512],[-116.52656,49.13175],[-116.52607,49.1312],[-116.52565,49.13083],[-116.52525,49.1304],[-116.52505,49.13011],[-116.52381,49.12725],[-116.52362,49.12671],[-116.52358,49.12627],[-116.52355,49.12084],[-116.52353,49.1186],[-116.52354,49.11721],[-116.52352,49.10888],[-116.52348,49.1083],[-116.52335,49.10797],[-116.52317,49.10773],[-116.52295,49.10753],[-116.5217,49.10667],[-116.52113,49.10629],[-116.52028,49.10566],[-116.51991,49.10529],[-116.5196,49.10486],[-116.51929,49.10423],[-116.51908,49.10283],[-116.51885,49.10171],[-116.51822,49.10057],[-116.51751,49.09912],[-116.51704,49.09824],[-116.51662,49.09779],[-116.51408,49.09778],[-116.51343,49.09777],[-116.51343,49.0975]],"directions":[{"text":"Continue onto Taku Dr for 350 m (29 seconds)","point":[-133.7022,59.56631]},{"text":"Turn slight right onto Mill St for 150 m (18 seconds)","point":[-133.70308,59.56869]},{"text":"Continue onto 1st St for 100 m (13 seconds)","point":[-133.70225,59.56994]},{"text":"Turn right onto Watson Ave for 80 m (7 seconds)","point":[-133.70293,59.57087]},{"text":"Turn slight left onto 2nd St for 450 m (39 seconds)","point":[-133.7016,59.57113]},{"text":"Turn right onto Discovery Ave for 750 m (54 seconds)","point":[-133.70411,59.57484]},{"text":"Continue onto Surprise Lake Rd for 1.2 km (55 seconds)","point":[-133.69138,59.57711]},{"text":"Turn right for 9.3 km (13 minutes 53 seconds)","point":[-133.67076,59.58072]},{"text":"Continue onto Sanca Creek FSR for 150 m (12 seconds)","point":[-116.72495,49.37864]},{"text":"Turn left onto Hwy 3A for 300 m (17 seconds)","point":[-116.72638,49.37921]},{"text":"Continue onto Sanca Creek Bridge for 45 m (2 seconds)","point":[-116.72644,49.37657]},{"text":"Continue onto Hwy 3A for 13 km (12 minutes 48 seconds)","point":[-116.72664,49.37617]},{"text":"Continue onto Boulder Creek Bridge for 35 m (2 seconds)","point":[-116.65372,49.28291]},{"text":"Continue onto Hwy 3A for 9.1 km (8 minutes 6 seconds)","point":[-116.65361,49.28262]},{"text":"Turn slight right onto Boulder Creek Bridge for 70 m (3 seconds)","point":[-116.59646,49.21448]},{"text":"Continue onto Hwy 3A for 13 km (10 minutes 9 seconds)","point":[-116.59625,49.21386]},{"text":"Continue onto Northwest Blvd for 2.4 km (2 minutes 43 seconds)","point":[-116.52353,49.1186]},{"text":"Turn left onto Vancouver St for 250 m (20 seconds)","point":[-116.51662,49.09779]},{"text":"Turn right onto 10th Ave for 30 m (2 seconds)","point":[-116.51343,49.09777]},{"text":"Finish!","point":[-116.51343,49.0975]}]}

**Comment by mraross** [comment]
Also fails on victoria to vancouver:
https://routerdlv.api.gov.bc.ca/directions.json?apikey=11dd756f680c47b5aef5093d95543738&criteria=fastest&roundTrip=false&points=-123.3647222%2C48.4283334%2C-123.1138889%2C49.2611112

**Comment by cmhodgson** [comment]
The cause of this problem was that the router uses the "base" roads geojson file, not the "post" file which includes the generated address ranges (because it doesn't need them); however the base roads geojson file had not been copied into the delivery data location because it was not required fort he geocoder; and I assumed that it had been. This resulted in the "old" "base" roads file being used in conjunction with the "new" intersections file, and intersections that were present in the "old" roads but not present in the "new" intersections ended up at 0,0, causing this "portal" effect. 

After uploading the "new" "base" roads file, and restarting the router, this problem is gone.

**Comment by mraross** [comment]
Verified in delivery
