### ISSUE TITLE
Incomplete route shown as completed even though missing ferry route

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#227]
From: 89 Nyberg Rd, Christina Lake, BC
    To:  3144 Boat Access West Side, Christina Lake, BC

**Comment by cmhodgson** [comment]
There is no ferry, that is the closest segment to 3144, and apparently it is within graphhopper's tolerance (it doesn't know there is water in between). Try 3270 Boat Access West Side, Christina Lake, BC and see how it picks a different road as the "access point". Given that we are using "access points", we may be able to tight en the tolerance a bit, however this will certainly hinder the usability of the lat/lon based input. The maximum allowable tolerance isn't clear but is at least 1km. I think it may be based on the limitations of the specific index type used (Graphopper has several and I'm not sure which one it is using). This is the index used to take the input points and determine which segment they are on.
