### ISSUE TITLE
Optimizing a 2-point route should skip optimization since there are no waypoints to reorder

### ISSUE THREAD

**Issue by cmhodgson** [bcgov/api-specs#228]
Optimize the optimizer by not calculating a route matrix and optimizing it when there are no choices to make.

Also, return a routeFound=false with -1 distance when any of the points are not route-able.

**Comment by cmhodgson** [comment]
Done and in delivery now. You can clearly see that it takes much less time to optimize a 2-point route (generally the same time has not-optimized) than a 3-point route. It is actually tempting, for optimizing a 3-point route, to shortcut it by just doing the two possible routes (1-2-3 and 1-3-2) rather than the full matrix and optimization process. Whichever of the two is shorter/faster, we would have to do anyway, to get the final route and directions, and doing the other is certainly faster than doing the matrix AND the optimization. 
I think it probably stops there... as there are six alternatives routes at the 4-point level: 1-2-3-4, 1-2-4-3, 1-3-2-4, 1-3-4-2, 1-4-2-3, 1-4-3-2, this is probably not enough faster to do them all than to do the matrix and the optimization.

**Comment by mraross** [comment]
Verified in test
