### ISSUE TITLE
non-civic addresses have no accessPoints

### ISSUE THREAD

**Issue by cmhodgson** [bcgov/api-specs#229]
/sites/nearest?locationDescriptor=accessPoint returns 0,0 albers if no AccessPoint exists
This is a problem exposed by clicking the random button on the router and it picks a site with a non-civic access point and asks for it's access Point. It should fall back to the parcelPoint in this case.

**Comment by cmhodgson** [comment]
This problem was fixed when we made it so that locationDescriptor=accessPoint made the query use an accessPoint-based spatial index. NCAPs without an accessPoint cannot be found in this case. However, if you lookup the site by its ID or name, and ask for locationDescriptor=accessPoint, you will get the Albers 0,0 location. I wonder if NCAPs should have their accessPoint set to the parcelPoint if  they have no accessPoint, so that such sites can still be found be queries like nearest?locationDesecriptor=accessPoint .
I would like some advice on whether you agree and if so, whether we should be assigning this access point into the Block Assignment and Address Range generation step (writing the accessPoint coordinates in the site_Hybrid.csv file ) or as a default assignment when loading the address ranges during the geocoder startup?

**Comment by cmhodgson** [comment]
Alter data load to populate empty APs with the associated Site Point. Also update range generation process to do the same and write it to site_hybrid.csv file.

**Comment by cmhodgson** [comment]
This fix is live in production right now, I'm not sure why this ticket never got closed. Notice that the following link to the non-civic site on discovery island has the same location whether you ask for access point or parcel point, and it is the correct location, not (0, 0):

https://apps.gov.bc.ca/pub/geocoder/sites/53671391-37ff-44a4-b06d-ff7a44c7f56f.json?locationDescriptor=accessPoint

https://apps.gov.bc.ca/pub/geocoder/sites/53671391-37ff-44a4-b06d-ff7a44c7f56f.json?locationDescriptor=parcelPoint

**Comment by mraross** [comment]
Verified in prod
