### ISSUE TITLE
Add an excludeUnits flag to sites/within, sites/near, and sites/nearest

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#23]
if excludeUnits=true, exclude all units from results. For example, given that 955 13th Ave, Valemount, BC is located at (-119.2567793,52.8239806), a sites/within?excludeUnits=true query centred on this point will return 955 13th Ave, Valemount, BC but not the 36 units in the building located at the same address.

Subsites that aren't units should not be excluded since they typically have their own location (e.g., SUB at UVIC)

In the future, excludeUnits=true could exclude all units only if the have the same location as their parent.

**Comment by cmhodgson** [comment]
Test Url: http://delivery.apps.gov.bc.ca/pub/geocoder/sites/near.html?excludeUnits=true&point=-119.2567793,52.8239806

**Comment by mraross** [comment]
The following query fails:
http://delivery.apps.gov.bc.ca/pub/geocoder/sites/within.kml?excludeUnits=true&bbox=-123.3735818091089,48.40745042029638,-123.3535376419002,48.41658312303552&WIDTH=1374&HEIGHT=943

**Comment by cmhodgson** [comment]
I think this is caused by a data issue which has since been fixed, but will require re-processing to test.

**Comment by cmhodgson** [comment]
Works now in delivery.

**Comment by mraross** [comment]
Verified in delivery.

**Comment by mraross** [comment]
Verified in Test.
