### ISSUE TITLE
nearest stop doesn't terminate if one of the points is disconnected from the network

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#230]
Using demo app at https://cmhodgson.github.io/ols-devkit/ols-demo/index.html?test=true

In Route tab, check nearest stop, then enter the following addresses:

   61755 Nahatlatch FSR, Boston Bar, BC
   1485 Boston Bar Trail, Merritt, BC
  15150 Powell Lake, Powell River, BC

System will display a Calculating Route message and never complete.

**Comment by cmhodgson** [comment]
This is now handled more clearly. In Delivery and test.

**Comment by mraross** [comment]
Verified in Test
