### ISSUE TITLE
Allow each platform(e.g. delivery, test, production) to have its own logging settings

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#24]
Enable build-time logging configuration in Maven.
At least two different logging configurations (dev and prod) are required. In order to ensure that the correct logging configuration is enabled for the platform, use a maven profile to select which logging config to copy into place at build time, as per Leo's suggestion:

<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-resources-plugin</artifactId>
            <version>2.5</version>
            <executions>
                <execution>
                    <id>log4j</id>
                    <phase>process-resources</phase>
                    <goals>
                        <goal>copy-resources</goal>
                    </goals>
                    <configuration>
                        <outputDirectory>output_directory</outputDirectory>
                        <resources>
                            <resource>${log4j.file}</resource>
                        </resources>
                    </configuration>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>

<profiles>
    <profile>
        <id>dev</id>
        <activation>
            <activeByDefault>true</activeByDefault>
        </activation>
        <properties>
            <log4j.file>path_to_file_A</log4j.file>
        </properties>
    </profile>
    <profile>
        <id>prod</id>
        <properties>
            <log4j.file>path_to_file_B</log4j.file>
        </properties>
    </profile>
</profiles>

**Comment by cmhodgson** [comment]
I've used a similar but different approach to allow maven to select a different log4j.properties file based on which profile (-Pdeliv, -Ptest, -Pprod) is selected. The deliv logging config is set to include debug info, while the test and prod only include warnings and up.

**Comment by cmhodgson** [comment]
I think Leo will want to confirm that this is doing the right thing in the various environments.

**Comment by ll911** [comment]
test/prod log4j value seems fine.



On Sep 21, 2016, at 11:25 AM, Chris Hodgson <notifications@github.com<mailto:notifications@github.com>> wrote:


I think Leo will want to confirm that this is doing the right thing in the various environments.

**Comment by ll911** [comment]
@cmhodgson can you update the log path to a relative one instead of absolute? e.g use `${CATALINA_BASE}/logs/bgeo.log`

**Comment by cmhodgson** [comment]
Ok I've committed this change.

**Comment by mraross** [comment]
verified
