### ISSUE TITLE
Disconnected route stop causes optimal route to fail

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#245]
Using demo app in test:

https://cmhodgson.github.io/ols-devkit/ols-demo/index.html?env=tst

Throw Sidney island together with some civic addresses in Victoria and the app will correctly say:

    No route exists in the BC Digital Road Atlas

Check Optimize Order and app will incorrectly return the following error:

   An unexpected server error occurred; No response from server. Error retrieving route results, please try your route again

**Comment by cmhodgson** [comment]
The router wasn't handling the situation where it was unable to optimize the order of the points because it couldn't calculate the distance between the points. I've modified it to now handle this case. This will require a delivery of the router.

**Comment by mraross** [comment]
Ok. Now we have to wait until end of month for the delivery thaw.

**Comment by cmhodgson** [comment]
This is fixed now in delivery:
https://cmhodgson.github.io/ols-devkit/ols-demo/index.html?env=dlv
