### ISSUE TITLE
In route planner, add a resource that represents the graph voronoi of a set of points

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#248]
Given a set of points, snap the points to the nearest road, find the graph voronoi and generate the appropriate set of polygons such that any point within the polygon, when snapped to the nearest road, is closer by road to its centre point than any other voronoi region.

Input parameters include:
points - a list of unique points; duplicate points will be ignored
bbox- an optional bounding box specifying the maximum extent of the road network that should be analysed. Can't be used with geomark present.
geomark - a geomark containing a single polygon that defines the maximum extent of the road network that should be analysed. Can't be used with bbox present.

router.api.gov.bc.ca/voronoi should return a list of voronoi regions where each region has a centre location and a polygon.

**Comment by mraross** [comment]
References
Scalable Exact Visualization of Isocontours in Road Networks via Minimum-Link Paths
http://drops.dagstuhl.de/opus/volltexte/2016/6349/pdf/LIPIcs-ESA-2016-7.pdf

**Comment by cmhodgson** [comment]
An additional parameter would be an optional bounding polygon (using geomark) or bbox, limiting the outside bounds of the service area calculation.

**Comment by mraross** [comment]
Should the resource be called serviceAreas or Voronoi?

**Comment by mraross** [comment]
Issue moved to [bcgov/ols-router #42](https://github.com/bcgov/ols-router/issues/42) via [**ZenHub**](https://www.zenhub.com/)
