### ISSUE TITLE
in online geocoder, get street missing fault instead of civic number missing

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#25]
in online geocoder in delivery, enter the following:

```
royal jubilee hospital -- bay st victoria bc
```

and you will get the correct match:

```
royal jubilee hospital -- 1952 bay st victoria bc
```

but the wrong fault:

```
STREET missing instead of CIVIC_NUMBER missing
```

**Comment by mraross** [comment]
The following addressString correctly returns a missing-street fault:
```
royal jubilee hospital -- victoria bc
```
The following addressString correctly returns missing street and locality faults:
```
royal jubilee hospital -- bc
```
and the following correctly returns missing street, locality, and province faults:
```
royal jubilee hospital --
```

**Comment by mraross** [comment]
Rejected

royal jubilee hospital -- bay st victoria bc

now returns the following faults
[STREET_NAME.notMatched:12, CIVIC_NUMBER.missing:10]

so civicNumber.missing is correct but streetName.notMatched is wrong

**Comment by cmhodgson** [comment]
Fixed it harder this time.

**Comment by cmhodgson** [comment]
Working in delivery now using test query above.

**Comment by mraross** [comment]
Verified in delivery using the following request:
http://delivery.apps.gov.bc.ca/pub/geocoder/addresses.html?addressString=royal%20jubilee%20hospital%20--%20bay%20st%20victoria%20bc

**Comment by mraross** [comment]
verified in test
