### ISSUE TITLE
Add support for unit number ranges in DataBC reference address list

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#250]
We can either have a new unit number range attribute or allow unit ranges in the current unitNumber attribute

1. New unitNumberRange
unitDescriptor,unitNumber,unitNumberSuffix,unitNumberRange
Suite,,,"100-119,200-219,300-319,400-419"
Suite,,,"100-119,200-219,300-319,400-419"
Suite,,,"100-119,200-219,300-319,400-419"
Suite,,,100,A,,
Suite,,,100,A,,
Suite,,,100,A,,

2. Allowing unit ranges in unitNumber attribute
unitDescriptor,unitNumber,unitNumberSuffix
Suite,,,"100-119,200-219,300-319,400-419",
Suite,,,"100-119,200-219,300-319,400-419",
Suite,,,"100-119,200-219,300-319,400-419",
Suite,,,100,A
Suite,,,100,A
Suite,,,100,A

**Comment by mraross** [comment]
Add support for unit number prefix which may contain a single alphabetic character or list of alphabetic characters and ranges. Unit number prefix represents a building name and will be merged into unitNumber.
Here are some examples:
unitNumberPrefix,unitNumberRange
A-C,100-199

means unitNumbers A100-A199, B100-B199, and C100-C199

**Comment by mraross** [comment]
Agreed on the following:
1. Add a unitNumberPrefix field  that supports single letter ranges (e.g., A-G)
2. Extend existing unitNumber field to support a list of constants and ranges (.e.g. 100-112,114-120,130)

**Comment by gleeming** [comment]
Added support for multiple unitNumber numeric ranges and multiple unitNumberPrefix single letter ranges.

For example unitNumberPrefix ="r-S,W" and unitNumber="600-602,700-701" produces records with full unit names of: R600, R601, R602, R700, R701, S600, S601, S602, S700, S701, W600, W601, W602, W700, W701 

Note that there were no DataBC records processed for inclusion in the v3.4 deployment

**Comment by mraross** [comment]
Verified
