### ISSUE TITLE
Rework/cleanup parts of the data processing for efficiency gains

### ISSUE THREAD

**Issue by gleeming** [bcgov/api-specs#255]
1) Remove AP_ID field from files and site prep FME scripts as this is deprecated (formerly used as a database table key).  Note that the geocoder code will also need to be modified as it currently tests for presence/absence of the ID (to distinguish interpolated locations).  An alternate approach (boolean or subclass) in Java could be implemented instead.

2) Remove Parcel Point field from files and site prep FME scripts as this is no longer needed for our street-only geocode approach.

3) Rework the site prep scripts to create a reduced file of just the unique street names for geocoding.  A name ID would need to be added onto the master address list (geocode_Hybrid.csv) to facilitate the relink.  The site loader prep FMW script will also need to be modified to accommodate this new join.  Overall this will result in significantly fewer batch candidates to geocode, and a more efficient join (and less memory) for subsequent processing.

**Comment by gleeming** [comment]
- unused attributes have been removed from pre-range generation files
- unique name approach was implemented and significantly reduces the batch time required

**Comment by mraross** [comment]
Verified
