### ISSUE TITLE
Reduce address data load file sizes by switching from CSV file format to TSV

### ISSUE THREAD

**Issue by cmhodgson** [bcgov/api-specs#259]
While working on another issue it was recognized that the CSV file sizes (used for both intermediate and final data files for the geocoder sites) could be reduced by 30% by not outputting unneeded quote characters. We believe that this will not affect the existing CSV reading code as it already handles this, we simply need to make a change to the output code - this affect both FME outputs and the BAARG output. The reduced input file size will reduce startup time and may have a minor positive effect on processing time, while also saving disk space.

**Comment by mraross** [comment]
Wouldn't adopting tab-separator value format have the same effect with less effort?

**Comment by cmhodgson** [comment]
Yes that would be a good option. I think these were originally intended to be human-manipulable files and TSV is marginally less friendly than CSV but I don't think that this is really a requirement anymore.

**Comment by cmhodgson** [comment]
My part of this is done. Saves about 18% space, reducing from site_Hybrid_post.csv at 432MB down to site_Hybrid.tsv at 359MB. Should have a similar savings on the "pre" file site_hybrid.csv which is currently 540MB. Note: all sizes based on Sept 2017 data. The rangebuilder and geocoder will both look for .tsv files but will fall back on .csv files if no .tsv is available, making the transition easier and allowing for ease of use of historical data for testing/comparison.

**Comment by mraross** [comment]
Brilliant.

**Comment by gleeming** [comment]
The site_Hybrid CSV file was converted to a TSV but it had little impact on file size as the original format had very few double quote cases.

**Comment by mraross** [comment]
Verified in test
