### ISSUE TITLE
Issues handling records with blank unit designators (UDs)

### ISSUE THREAD

**Issue by gleeming** [bcgov/api-specs#260]
Some custodians provide a unit designator (e.g. APT) while others do not.  For admin flexibility, Cassandra has a parameter (defaultUnitDesignator=UNIT) used by the geocoder application that applies a predetermined unit designator (UD) to subsites where one was not provided from source.  It was just discovered that this flexibility is a problem for site processing in certain cases.

In the FME site prep scripts, duplicate address resolution is based on unique combinations of street, locality, civic and unit components.  This allows us to distinguish between cases like UNIT 4 -- 1207 Douglas St, FLOOR 4 -- 1207 Douglas St, PH 4 -- 1207 Douglas St, etc.

Unfortunately allowing flexibility to set a default UD at run time to entries missing one has an unwanted side effect.  Otherwise identical subsite addresses from two sources are treated as being different when the UD of one is blank.  For example BCA has an address of UNIT 207 -- 225 FRANCIS WAY while GSR has an address of 207 -- 225 FRANCIS WAY.  For duplicate resolution, these are currently considered to each be unique addresses to the site prep and end up both being retained as two distinct sites.  The geocoder subsequently adds a default UD to the GSR entry at run time and then on output we have what looks like two sites at the same address.

Example of the above in delivery: maxResults=5 for UNIT 207 -- 225 FRANCIS WAY New Westminster BC.  Cases probably also exist in production, though I don't know the extent of the issue.  It may only apply to GSR subsites.

To resolve this the site prep scripts should probably be updated to always set a default UD of UNIT to subsite records without one before reconciliating duplicates.  This would likely deprecate the cassandra defaultUnitDesignator parameter as FME would always prepopulate a UD.

**Comment by cmhodgson** [comment]
This doesn't completely deprecate the parameter as there are other cases where the default is used - at least there are in the code, possibly they are all dead code now. However it certainly makes it even less likely that we would ever want to change the parameter.

**Comment by mraross** [comment]
If a geocoding request has an addressString like "1-120 Main St", the parser needs to add the defaultUnitDesignator before looking for a match, no?

**Comment by gleeming** [comment]
Yes that makes sense, so the parameter will still be useful in standardizing user input, but not for preprocessing of data.

**Comment by cmhodgson** [comment]
No, it doesn't add the default designator, it matches without, and penalizes for the missing designator.

**Comment by mraross** [comment]
But how does it know which unit designator to look for and add to fullAddress?

**Comment by cmhodgson** [comment]
Here is an example of a unit-designator-free query working in delivery:
http://delivery.apps.gov.bc.ca/pub/geocoder/addresses.html?addressString=1-120%20Main%20St

Not sure what else we can really test here.

**Comment by mraross** [comment]
Verified in prod
