### ISSUE TITLE
In occupants resources, add support for an occupant separator in addressString and fullAddress

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#261]
In addressString parameter of occupants/addresses, recognize an occupant separator that appears between the occupant name and the site address. For example, given an occupant separator of "**", a valid addressString value is as follows: 

Cascadia Board Co. ** Saanich, BC

in responses of all occupants resources, fullAddress should include an occupant separator as in the following:

Cascadia Board Co. ** UNIT 69 -- 770 Vanalman Ave, Saanich, BC

**Comment by mraross** [comment]
This will require documenting a new variant of single-line format for occupants:

[occupant name ++ ] <site address>

**Comment by mraross** [comment]
geocoder is putting in an extra comma after occupant separator (**)

Cascadia Board Co. **, UNIT 69 Cascadia Board Co. -- 770 Vanalman Ave, Saanich, BC

**Comment by cmhodgson** [comment]
Looks good in delivery.

**Comment by mraross** [comment]
Verified in delivery
