### ISSUE TITLE
Update router api spec to reflect changes in 1.3 release 

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#263]
1. All resources now support POST
2.  In distance/betweenPairs, add a maxPairs input parameter that  specifies the maximum number of pairs to return for each toPoint.  Pairs are ordered by distance/time from fromPoint. For example, given 1 fromPoint, and 10 toPoints,  and maxPairs=1 , return the nearest toPoint to the fromPoint. Given 3 fromPoints and 10 toPoints, maxPairs=3 means return the 3 nearest toPoints to each fromPoint.
3.  All request responses now include a routeFound Boolean parameter that, if true, indicates a route exists that connects all route points; false otherwise

**Comment by banders** [comment]
@mraross @BK01 I Added POST support to all operations and added the new maxPairs param to the "distance/betweenPairs" path.  We don't currently document response formats for any API specifications, so I didn't make any change to address point 3 above.

We currently have two versions of the router API spec file.  One is in OpenAPI v2 format, the other is in v3 format.  We are transitioning to OpenAPI v3, so I have only modified that version of the spec. The new file is here:
 https://github.com/banders/api-specs/blob/upgrade-to-openapi3/router/router.json

I didn't have any luck getting the new "maxPairs" parameter to work.  Using the example  "toPoint" and "fromPoint", I always get 4 pairs returned, even when I request a different number.  Can you confirm that "maxPairs" is the correct parameter name and that the current production version of the router supports this param?

**Comment by mraross** [comment]
Did you use routertst or routerdlv? It isn't in prod yet.

**Comment by mraross** [comment]
Here's an example extracted from the Network monitor of Firefox while running the betweenPairs demo app located at https://cmhodgson.github.io/ols-devkit/ols-demo/betweenPairs.html?env=tst

Request: POST https://routertst.api.gov.bc.ca/distance/betweenPairs.json

Request body:
fromPoints=-123.4860076%2C48.4345191%2C-123.493518%2C48.4493955&toPoints=-123.4701013%2C48.4856558%2C-123.4896108%2C48.411384%2C-123.352087%2C48.4111347%2C-123.3865522%2C48.4435639&criteria=fastest&maxPairs=1

**Comment by banders** [comment]
@mraross That for confirming that the "maxPoints" param isn't yet supported in Prod.  That explains why my tests didn't succeed.

**Comment by mraross** [comment]
verified in prod
