### ISSUE TITLE
Identical content jobposting.yaml and jobposting_swagger2.yaml

### ISSUE THREAD

**Issue by darosh** [bcgov/api-specs#264]
Hoping this is not duplicated issue. Both `jobposting.yaml` and `jobposting_swagger2.yaml` are `Swagger 2.0` with identical content. 

Can you explain the duplication please? 

I am asking because this repo is automatically consumed by https://github.com/APIs-guru/openapi-directory scripts 

Thank you.

**Comment by BK01** [comment]
@darosh You are correct that both specs are identical at the moment. However, the 'jobposting_swagger2' files will soon serve as a backup of the swagger 2.0 version spec, and the 'jobposting' yaml & json file will continue to serve as the master. Shortly, we will be converting our api-specs to use OpenAPI 3 spec with version 3.4.4 of swagger-ui. The presence of '_swagger2' files should only occur in 2 or 3 of our specs where clients have a need for an older api console viewer.
