### ISSUE TITLE
in geocoder admin, add support for export/import configuration data

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#27]
on Aug 4, 2016, cmhodson wrote:

> I propose an "export config data" button on the admin UI which creates a multi-csv file that can be passed into a matching "import config data" button. This would allow Refractions to easily stay up-to-date with any config changes made on the government side. All future config changes would go through Michael and be made on the government side before being transferred back to refractions. When a new release is delivered, the most current configuration would be exported from the gov and the file included in the build, to be used in the case of populating an new/empty cassandra DB.
> 
> Presently there is one csv file for each table which are used to populate a new/empty cassandra DB, and we need a way to keep these up to date - this approach solves this problem as well.

**Comment by ll911** [comment]
@cmhodgson @mraross I would prefer import/export as json file, it can be edited/verified with JSON editor like http://www.jsoneditoronline.org/ or https://chrome.google.com/webstore/detail/json-editor/lhkmoheomjbkfloacpgllgjcamhihfaj?hl=en

**Comment by mraross** [comment]
I agree with Leo. JSON accommodates changes to the config file schema more gracefully than csv.

**Comment by cmhodgson** [comment]
I can't believe you are telling me that JSON is easier to edit than CSV but if that's what you prefer I can do that.

**Comment by mraross** [comment]
I’m not. Leo is. I’m saying that because JSON is self-describing, if new properties are added to the schema, a json ready can read it without problem.

**Comment by cmhodgson** [comment]
Here is a sample of the export I intend to use, please let me know if this is acceptable.
(note it downloads as a .json but I cannot attach .json files here so it has been renamed as .txt)
[ols_admin_config_export.txt](https://github.com/bcgov/api-specs/files/720749/ols_admin_config_export.txt)

**Comment by mraross** [comment]
Using http://jsonlint.com/ , I load the json file, press validate JSON, and get the following error:

SyntaxError: Duplicate key 'BGEO_ABBREVIATION_MAPPINGS' on line 1419

**Comment by mraross** [comment]
Leo, please review json format.

**Comment by cmhodgson** [comment]
Revised export sample:
[ols_admin_config_export.txt](https://github.com/bcgov/api-specs/files/720816/ols_admin_config_export.txt)

**Comment by mraross** [comment]
jsonlint says format is valid so it looks good to me.

**Comment by ll911** [comment]
structure and format looking good, @cmhodgson, @mraross did you need to verify the content?

**Comment by cmhodgson** [comment]
This is an example as extracted from my local cassandra. The intent that once this is added to the admin UI, I can extract exactly what is in YOUR cassandra, and include it in my delivery as the default starting data (in the case of starting from scratch with an empty cassandra DB). The contents are not important. You specifically requested that I use JSON format; I just wanted to make sure this is acceptable.

**Comment by mraross** [comment]
Would a date/timestamp be useful to be able to tell when an extract was done?

**Comment by ll911** [comment]
@cmhodgson ok, that's fine. @mraross date/timestamp will be created when file is created on filesystem. is there way to ensure the integrity of the file?

**Comment by cmhodgson** [comment]
I like the idea of including a timestamp, as the file's create date is not always reliable in the case of copying, etc. As far as the integrity goes; it will have to parse as valid JSON, it is unlikely that a random section could be lost and still be valid JSON. I think we actually need/want to be able to make changes to the file, as that is how I would add a new config parameter. I could include a row count per table as a basic integrity check, that would be easy enough to modify when adding an additional record.

**Comment by mraross** [comment]
I like the table row counts for integrity provided you use them on import to verify the expected number of rows were present.

**Comment by cmhodgson** [comment]
Yes, of course the intent is to validate the actual number of rows of data against the expected number before modifying the actual database. I've also provided an option to just validate an export file, possibly useful.

**Comment by mraross** [comment]
Validation support would be very useful.

**Comment by cmhodgson** [comment]
Confirmed in delivery.

**Comment by mraross** [comment]
Did an export then a validation which produced this report:

Validate Configuration
Validation Successful

Messages

    BGEO_CONFIGURATION_PARAMETERS count: 117 (matches expected)
    BGEO_ABBREVIATION_MAPPINGS count: 324 (matches expected)
    BGEO_UNIT_DESIGNATORS count: 18 (matches expected)
    BGEO_LOCALITY_MAPPINGS count: 4596 (matches expected)

My understanding is the check count in the file matched the actual count for each category of config variable. Could this be displayed a little more explicitly as in:

                                         File                      File                              Geocoder
                                         Check Count       Actual Count              Actual Count
        Config parameters       117                     117                              117
Abbreviation mappings       324                     324                              324 
           Unit designators         18                       18                                18
        Locality mappings     4596                    4596                             4596

**Comment by cmhodgson** [comment]
After our phone discussion Michael and I agreed that the "validate" step would perform a diff between the file and the current config data, and show the specific differences, ie. keys with different values in the two places, or keys that exist in one but not the other. In addition to providing the summary count data specified above.

**Comment by cmhodgson** [comment]
![configvalidation](https://cloud.githubusercontent.com/assets/11282931/23045050/cf0e076e-f457-11e6-8238-e3a09216af9c.png)
How does this look Michael?

**Comment by mraross** [comment]
Looks great. Can you include the config file name and its creation date in this report?

**Comment by cmhodgson** [comment]
The File name and creation date are now included at the top of the validation/diff report.
The import function now requests a confirmation before submitting.
Confirmed in Delivery.

**Comment by mraross** [comment]
copyright character in file not matching live config. Is there a character encoding issue here?

![screenhunter_17 feb 23 12 25](https://cloud.githubusercontent.com/assets/11318574/23277610/517bc50e-f9c3-11e6-90dd-cf938e5051f7.jpg)

**Comment by mraross** [comment]
The copyright character looks fine in the config file when I load it into pspad. Maybe its just the text comparison code?

**Comment by cmhodgson** [comment]
The export was in the default 8859-1 encoding instead of UTF-8 which I was expecting the input to be in. I updated it to export in UTF-8, now the comparison works. Just waiting to get it built in delivery...

**Comment by mraross** [comment]
Export and validation now work since validation now reports no differences.

**Comment by mraross** [comment]
Verified
