### ISSUE TITLE
Replace all UUIDs with shorter IDs

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#273]
siteID, occupantID, and intersectionID can all be a lot shorter since they are recreated from scratch every month.  In others words, they need to be unique but not immutable.

How about something like 

   `yydddnnnnnnn` 

where yy is 2000+yy
           ddd is the day of year (e.g., 001-366)
           nnnnnnnn is an seven character sequence number between 0000001 and 9999999

This makes an id 12 characters instead of 36 characters. Having the day of year in there makes sure that members of two different data preps won't collide with each other.

A short ID will save 26 characters in a simple site response, 52 characters in a subsite response, and 52 or 78 characters in an occupant response (depending on whether occupied site is a subsite or not).

A short ID will also save 72% in space needed for siteIDs in the sid2pid table.

**Comment by cmhodgson** [comment]
Are we giving up all hope of ever having immutable id's? Perhaps a better approach to space saving is to zip the csv files and/or enable compression filtering on the server side? Not entirely sure how well that works with a rest API... but not sure how far backwards we want to go with our IDs.  In memory the Uuids are stored as 4 32 bit ints so yes we could cut that down to possibly a single int... I don't know that the Day of year is really unique enough especially if we ever get into regular monthly processing, as we might imagine things happening on the same date regularly...

**Comment by mraross** [comment]
So maybe throwing the baby out with the bathwater is a bit much after all. Let's just keep uncompressed UUIDs and focus on trying to get siteIds into the geocoder API without incurring the cost of access control.
