### ISSUE TITLE
Refine geocoder api gateway access policies

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#277]
The api gateway allows us to set access policy for anonymous access at the resource level. Here is my proposed policies:

1. 1,000 per minute for all resources except parcels/pids

2. parcels/pids should not be accessible anonymously

3. parcels/pids should only be accessible to a special group of users

This policy can be implemented now.

**Comment by cmhodgson** [comment]
I think you maybe meant to assign this to Leo?

**Comment by mraross** [comment]
Yes and I wanted your opinion too.

**Comment by ll911** [comment]
you wanna include 
/parcel/* there as well?

**Comment by mraross** [comment]
Doh! See above.

**Comment by cmhodgson** [comment]
Maybe a rate per hour would make more sense to allow for short bursts of high activity while still preventing abuse over a longer time.
It would be nice to leave as much open as you can to allow potential users to experiment, as opposed to locking the door entirely. With careful monitoring, when a problem occurs it can potentially be analyzed and appropriate actions take to lock out the offending usage.

**Comment by mraross** [comment]
@ll911

**Comment by ll911** [comment]
can you try in dlv? @cmhodgson @mraross
