### ISSUE TITLE
Search timestamp not being returned for addresses when choosing outputSRS=3005

### ISSUE THREAD

**Issue by gleeming** [bcgov/api-specs#283]
The searchTimestamp field is present for the output from the following
https://apps.gov.bc.ca/pub/geocoder/addresses.xhtml?minScore=50&maxResults=5&outputSRS=4269&echo=false&brief=true&autoComplete=true&addressString=3101+30+Ave%2C+Vernon%2C+&locationDescriptor=accessPoint

But if BC Albers projection is used then the searchTimestamp is just blank
https://apps.gov.bc.ca/pub/geocoder/addresses.xhtml?minScore=50&maxResults=5&outputSRS=3005&echo=false&brief=true&autoComplete=true&addressString=3101+30+Ave%2C+Vernon%2C+&locationDescriptor=accessPoint

This appears to affect other formats too, not just xhtml.

**Comment by mraross** [comment]
Verified in prod.
