### ISSUE TITLE
in geocoder/addresses, add support for a streetName.isHighwayAlias fault

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#29]
Allow a highway street name to be aliased without a penalty. Implement as a streetName.isHighwayAlias fault that can have its own penalty of zero. This allows the non-highway streetName.isAlias fault to still have a positive penalty.

Currently the query address:

5349 HWY 17, Saanich, BC 

returns the following:

5349 Patricia Bay Hwy, Saanich, BC

and a fault of [STREET_NAME.isAlias:1]

After this enhancement is implemented, the geocoder will return the same fullAddress but a fault of [STREET_NAME.isHighwayAlias:0]

**Comment by cmhodgson** [comment]
Test URL: http://delivery.apps.gov.bc.ca/pub/geocoder/addresses.html?addressString=5349%20HWY%2017,%20Saanich,%20BC

**Comment by mraross** [comment]
Verified in delivery
