### ISSUE TITLE
Fix the siteRetireDate for UNIT level results

### ISSUE THREAD

**Issue by gleeming** [bcgov/api-specs#291]
Currently site records in the processed files all have a blank retire dates since we don't have any source for setting a custom value.  The geocoder should automatically set a default date of Dec 31, 9999 for these cases.

CIVIC_NUMBER matches correctly return the default 9999-12-31 00:00:00.0.  However UNIT matches appear to be getting the changeDate returned as both the changeDate and siteRetireDate.  The link below can be used for testing as it returns both types of results.

https://geocoderdlv.api.gov.bc.ca/addresses.xhtml?addressString=UNIT%20207%20--%20225%20Francis%20Way,%20New%20Westminster,%20BC&maxResults=2

**Comment by cmhodgson** [comment]
This is fixed in delivery now. (snuck in with the /parcels/ apikey changes)

**Comment by mraross** [comment]
Verified in test

**Comment by mraross** [comment]
Updated test case and verified in delivery.
