### ISSUE TITLE
Unit number prefix treated as unit number suffix

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#292]
Here's an address that has a unit number prefix:

 UNIT A101 -- 17780 56 Ave, Surrey, BC

This would be transformed by data prep into the following:

UNIT 101A --  17780 56 Ave, Surrey, BC

This is incorrect. In Canada Post standard, A101 is treated as a unitNumber. In other words, CP allows a character at the beginning of a unit number to accomodate building names as letters.

**Comment by gleeming** [comment]
As it turns out, we do allow an optional single character at the beginning of a unit number.  A valid example is UNIT J205 1400 ALTA LAKE RD Whistler BC

**Comment by mraross** [comment]
Verified in production
