### ISSUE TITLE
Add Processing Date into Input Files and Response

### ISSUE THREAD

**Issue by cmhodgson** [bcgov/api-specs#294]
Add a processing date into ITN json files. This date would be validated to be the same on all read files in both the router and geocoder, and output in the header section of responses, next to the API version

**Comment by gleeming** [comment]
I've added 3 date fields to each of the GeoJSON street layers.  The feature type is called "dates" and looks something like:
{"name":"dates","type":"FeatureCollection"
,"crs":{"type":"name","properties":{"name":"EPSG:3005"}}
,"features":[
{"type":"Feature","geometry":null,"properties":{"ITN_VINTAGE_DATE":20180201,"BCGNIS_VINTAGE_DATE":20171201,"PROCESSING_DATE":20180213}}
]}

**Comment by mraross** [comment]
Looks good.

**Comment by gleeming** [comment]
I've also added a new ELECTORAL_AREA_DATE

**Comment by cmhodgson** [comment]
Do we want to return only the processing date in normal queries, with the other dates included in a specific date query?

**Comment by mraross** [comment]
Sounds reasonable.

**Comment by cmhodgson** [comment]
How about a field name of "processingDate"? It will be in the header next to searchTimestamp and executionTime. Just wondering if it needs to be more specific eg. "dataProcessingDate" or 
"baseDataDate"

**Comment by mraross** [comment]
I like baseDataDate

**Comment by mraross** [comment]
Verified in delivery

**Comment by mraross** [comment]
Verified in test
