### ISSUE TITLE
Distinguish between City of Langley and Township of Langley

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#299]
All addresses in the Township of Langley are returned with localityType set to City instead of Township. Change data prep scripts so that localityType is set to Township for addresses in Township of Langley (e.g., using a point in langley township polygon test). 

Gov't apps that use local jurisdiction to assign resources or taxes need this fixed.

**Comment by gleeming** [comment]
The left & right of each Langley road segment (1m offset at midpoint) is checked against a custom polygon.  Langley city gets a new locality ID of 1518.

**Comment by gleeming** [comment]
Custom handling in the block assignment and address range generator code was also required to support the locality distinction

**Comment by mraross** [comment]
Verified in delivery.
