### ISSUE TITLE
Geocoder, inconsistent responses to query depending on API use

### ISSUE THREAD

**Issue by pramsey** [bcgov/api-specs#3]
The same address, supplied to the geocoder in different ways, leads to different match precisions.

Broken into parts, the geocoder only returns a 'PROVINCE' level match result.

http://apps.gov.bc.ca/pub/geocoder/addresses.geojson?streetName=70A&streetType=AVE&unitNumber=BASEM&civicNumber=14375&localityName=SURREY&streetDirection=&provinceCode=BC

But glued together into a string, the geocoder happily consumes it (and produces the very parts used above) and provides a 'CIVIC_NUMBER' level of precision.

http://apps.gov.bc.ca/pub/geocoder/addresses.geojson?addressString=BASEM+--+14375+70A+AVE,+SURREY,+BC

**Comment by mraross** [comment]
@pramsey Hi Paul, Interesting bug you found. Have logged it into the geocoder issue tracker. Note that if you use BSMT instead of BASEM, you get the same result as using addressString.

http://apps.gov.bc.ca/pub/geocoder/addresses.xhtml?unitDesignator=bsmnt&streetName=70A&streetType=AVE&civicNumber=14375&localityName=SURREY&province=BC

**Comment by mraross** [comment]
Sorry, I meant if you use BSMNT instead of BASEM and you assign it to unitDesignator, not unitNumber, you get the same result as using addressString.

**Comment by mraross** [comment]
BSMT is actually the official abbreviation for basement and is a unitDesignator value, not a unitNumber value. The complete list of unitDesignator values is in the API console and the glossary.

http://apps.gov.bc.ca/pub/geocoder/addresses.xhtml?unitDesignator=bsmt&streetName=70A&streetType=AVE&civicNumber=14375&localityName=SURREY&province=BC

**Comment by mraross** [comment]
Added basem as an abbreviation for basement. Try this:

http://delivery.apps.gov.bc.ca/pub/geocoder/addresses.html?unitDesignator=basem&streetName=70A&streetType=AVE&civicNumber=14375&localityName=SURREY&province=BC

**Comment by pramsey** [comment]
Not sure I'm fond of `unitNumber` and `unitDesignator`, certainly makes things a little harder for anyone whose data aren't parsed out "just so".

http://delivery.apps.gov.bc.ca/pub/geocoder/addresses.html?unitNumber=basem&streetName=70A&streetType=AVE&civicNumber=14375&localityName=SURREY&province=BC

Also, how does UNIT_DESIGNATOR throw a "not matched" fault, when the returned `fullAddress` is "BSMT -- 14375 70A Ave, Surrey, BC"?

**Comment by cmhodgson** [comment]
I'm not sure if you should be getting the notmatched. I think the code is just doing a string.equals, not taking into account the possible abbreviation/aliasing. That said, the input unit designator is not a perfect match, so you should know about that so you can fix it.

Unless you have exactly the same fields as we do and are trying to follow the geocoder address model, you probably shouldn't be using the structured geocoder. It isn't much faster, and it's much pickier.

**Comment by pramsey** [comment]
Good advice that. It felt dirty to take my mostly-parsed strings and glue them together again just to get them re-parsed, but that's where I landed, and the results have been better since.

**Comment by cmhodgson** [comment]
The reality is that no matter what model we use internally or expose in the API, most users won't have the same model, and so someone will have to glue some parts together. Then we must be able parse them apart again, so why not just have one field...

**Comment by mraross** [comment]
Data suppliers should use the structured address because reference data should meet the highest of quality standards.
