### ISSUE TITLE
Distinguish between District of North Vancouver and City of North Vancouver

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#300]
All addresses in the District of North Vancouver are returned with localityType set to City instead of District. Change data prep scripts so that addresses within District of North Van have localityType set to District (e.g., using a point in North Vancouver District polygon test).

Gov't apps that use local jurisdiction to assign resources or taxes need this fixed.

**Comment by gleeming** [comment]
The left & right of each North Vancouver road segment (1m offset at midpoint) is checked against a custom polygon.  North Vancouver city gets a new locality ID of 1519.

**Comment by gleeming** [comment]
Custom handling in the block assignment and address range generator code was also required to support the locality distinction

**Comment by mraross** [comment]
Verified in delivery.

**Comment by mraross** [comment]
Verified in test.
