### ISSUE TITLE
optimal visitOrder array values are incorrect

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#301]
Startup up location services demo app in production and turn on network trace.

In route planner, enter the following stops in order (array index shown in square brackets):
1200 Douglas St, Victoria, BC    [0]
1020 View St, Victoria, BC          [1]
851 Broughton St, Victoria, BC  [2]
835 Fisgard St, Victoria, BC       [3] 
707 Fort St, Victoria, BC            [4]

Select Optimize Order. System will compute and display the correct optimal route line and directions but the visitOrder array contains values 0, 3, 2, 4, 1 which are incorrect. The visitOrder array values should be 0,4,2,1,3

**Comment by cmhodgson** [comment]
You are interpreting the visitOrder array values differently from how they are meant to be.
Imagine the visitOrder array is attached as a second column beside the stops. Then the value in the array tells you the position of that stop in the optimized route:

[0] 1200 Douglas St, Victoria, BC
[3] 1020 View St, Victoria, BC
[2] 851 Broughton St, Victoria, BC
[4] 835 Fisgard St, Victoria, BC
[1] 707 Fort St, Victoria, BC

I use the visit order in the UI to assign the stop numbers to each of the icons. This way is more efficient (for what its worth) as the array supports random access but the list of stops on the screen does not.

**Comment by mraross** [comment]
Will update the Route Planner Developer Guide appropriately.

**Comment by mraross** [comment]
Router developer guide has been updated to describe how visitOrder works.
router.json openapi specs have also been updated to include optimalRoute and optimalDirections resources. roundTrip parameter was also added to route and directions resources in specification.

**Comment by mraross** [comment]
Documentation verified in prod
