### ISSUE TITLE
Some blocks have incorrect direction of increasing civic numbers

### ISSUE THREAD

**Issue by cmhodgson** [bcgov/api-specs#303]
An example is:
1301 Douglas St, Victoria, BC

It returns a point at the 1399 end of the block. This is caused by all the address points being located at a single point on the block (typical in the situation of one large building spanning the block, or of sparsely populated rural areas with only one address point). In this situation it is impossible to tell which direction the civic numbers should increase in. The anchor points from RNF or other sources should help to resolve this but if the civic numbers are in the same range as the know address points, they can be ignored.

One way to work around this situation is to fall back on looking at the relative civic numbers of the sites closest to the end of the block (as opposed to looking at the relative positions of the highest and lowest civic numbers).

**Comment by cmhodgson** [comment]
I've implemented this fix and it does correct the specific example of the 1301 block of Douglas st in Victoria.

**Comment by cmhodgson** [comment]
Additionally, a smoothing process now compares the median of the known addresses on the blocks on either side of each block, and adjusts the direction of increasing addresses to be consistent. This makes approximately ~10,500 adjustments (hopefully mostly improvements).

**Comment by cmhodgson** [comment]
Confirmed in delivery for the specific example case of: 1301 Douglas St, Victoria, BC

**Comment by mraross** [comment]
Verified in prod

**Comment by mraross** [comment]
Verified in test
