### ISSUE TITLE
A single pid response from parcels/pids is a number instead of a string

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#316]
{"siteID":"3e5f8c40-d4c1-42e7-94be-287ae70dcb03","pids":024365491}

instead of

{"siteID":"3e5f8c40-d4c1-42e7-94be-287ae70dcb03","pids":"024365491"}

**Comment by cmhodgson** [comment]
Confirmed in delivery using Advanced Rest Client to provide the apikey header, using the URLs:
single PID response:
https://geocoderdlv.api.gov.bc.ca/parcels/pids/2d43cbeb-61ea-403e-b018-76cc1f76effc.json

multi-pid response:
https://geocoderdlv.api.gov.bc.ca/parcels/pids/3280bc5c-2a57-40c1-8830-4e51748b931c.json

no-pid response:
https://geocoderdlv.api.gov.bc.ca/parcels/pids/f2c6a5b8-dd9e-4b11-9efd-3b106a07337d.json

**Comment by mraross** [comment]
Verified in delivery

**Comment by mraross** [comment]
Verified in prod
