### ISSUE TITLE
Add localityType and electoralArea to brief response

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#317]
localityType is needed to differentiate some municipalities from same named townships and other types. For example, Langley Township and Municipality; North Vancouver District and Municipality.

electoralArea is needed because it is an address element that is not contained in fullAddress.

**Comment by cmhodgson** [comment]
Done.

**Comment by cmhodgson** [comment]
Confirmed in delivery. Note that the brief=true option only applies to HTML, JSON, and KML output formats

**Comment by mraross** [comment]
confirmed in test
