### ISSUE TITLE
Add locality mappings related to munis involved in #299 and #300

### ISSUE THREAD

**Issue by gleeming** [bcgov/api-specs#323]
1) create the following aliases to allow explicit string links and no penalty:
City of Langley    Maps to: Langley (1518) with confidence:    100
Township of Langley    Maps to: Langley (518) with confidence:    100
City of North Vancouver    Maps to: North Vancouver (1519) with confidence:    100
District of North Vancouver    Maps to: North Vancouver (519) with confidence:    100

2) consider cross-mapping the pairs to each other with a penalty
- e.g. Langley (Township) <-> Langley (City) at 80
- this way if someone explicitly geocodes ToL the result could still fall back on CoL but not without a fault
- addresses with unspecified locality types (e.g. just Langley) should continue just fine getting the best match from the geocoder

3) consider reviewing historical locality mappings (aliases and cross-references) and extending them
- abbotsford maps to Township of Langley (518); we probably want this and the other MVRD munis to also map to the new locality variants
- conversely, grouse mountain maps to District of North Vancouver (519); given its location we may not want it to also map to City of Vancouver

Once all of the mappings have been created we can get an export of the BC Gov environment and refresh ours to match.

**Comment by mraross** [comment]
Done. Didn't add grouse mountain => City of Vancouver as you suggested.

**Comment by mraross** [comment]
verified in test.
