### ISSUE TITLE
parcels/pids not returning a valid response when given an unknown siteID

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#326]
When given an unknown siteID, parcel/pids is giving a different response than sid2pid as follows:
HTTP 404
<!DOCTYPE html>
<html>
<head></head>
<body>
No site found with specified UUID.</body>
</html>

when given an unknown siteID, sid2pid in cpf returns the following:
HTTP 200
{
"sequenceNumber":1,
"siteID":"4280bc5c-2a57-40c1-8830-4e51748b931c",
"pids":null
}

Change parcels/pids so that it responds the same as sid2pid

**Comment by cmhodgson** [comment]
I think we may want to consider this to be a useful feature - It allows you to differentiate between the two cases:
1) You provided an invalid SID which is unknown to the system (likely out of date or typo'd) - this returns the 404
2) You provided a valid SID for which there just isn't an associated parcel - this returns a 200 with "pids":null

Granted, there may be a more preferable way to provided this distinction, but it is a valuable distinction which wasn't being made before in the CPF SID2PID. I believe this is the RESTful way to do it (with the 404) but another way might be to return a format-specific error message (or always JSON?) in the response (either still a 404 or as a 200).

**Comment by mraross** [comment]
I agree with the distinction. So, for this resource only,  I think we need to implement the errorFormat parameter for this resource where the choices are html or json and the default is html for backward compatibility with our current error handling.

This will give us a chance to try out a new, standard json error response format. I propose the google json error object as defined in https://google.github.io/styleguide/jsoncstyleguide.xml?showone=error#error

So in case 1 with no errorFormat parameter or errorFormat=html, the API responds as it does now. 
In case 1 with errorFormat=json, the API returns the following JSON error object:

{
  "apiVersion": "3.4",
  "error": {
    "code": 404,
    "message": "Site Not Found",
  }
}

**Comment by mraross** [comment]
Suggested to LTSA that MyLTSA turn interpolation off in geocoder requests for parcels by address. It can be left on for general map navigation.
