### ISSUE TITLE
Prevent routing on emergency lanes

### ISSUE THREAD

**Issue by gleeming** [bcgov/api-specs#328]
There are road features in ITN with street names of "emergency lane".  These are typically short connectors between divided segments and not at an intersection crossing.  While they are useful to model for emergency vehicle routing, they are not intended for general public use and our route planner.

An example is the connector about 60m NW from 4000 Seymour Pl building on the hill between the south- and north-bound lanes of Blanshard St.  More impactful cases exist on limited access divided highways, where unwanted and illegal u-turn routes can currently be created.

These emergency lanes mostly have a road class of lane (valid for general routing) so they can only be distinguish by their street name.  It is possible that there are other similar types of features in ITN that should be excluded from the network.

**Comment by mraross** [comment]
Issue moved to [bcgov/ols-router #41](https://github.com/bcgov/ols-router/issues/41) via [**ZenHub**](https://www.zenhub.com/)
