### ISSUE TITLE
router KML and GML output missing namespace declarations

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#345]
KML namespace declaration should be as follows:
`<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:gx="http://www.google.com/kml/ext/2.2" xmlns:kml="http://www.opengis.net/kml/2.2" xmlns:atom="http://www.w3.org/2005/Atom">`

**Comment by cmhodgson** [comment]
Not really a bug - problem with ARC display of xmlns in XML files.
