### ISSUE TITLE
geocoder json/geojson output, add a flag not to display null fields 

### ISSUE THREAD

**Issue by ll911** [bcgov/api-specs#349]
geocoder json/geojson output, add a flag not to display null fields 
e.g. `nullFields=false`

All clients need this to reduce result payload size and improve user experience

**Comment by mraross** [comment]
Issue moved to [bcgov/ols-geocoder #41](https://github.com/bcgov/ols-geocoder/issues/41) via [**ZenHub**](https://www.zenhub.com/)
