### ISSUE TITLE
Highway aliases for BC Assessment address cleanup in address prep scripts

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#35]
Cariboo Hwy 97 => Cariboo Hwy in 70 Mile House

means map streetName: Cariboo Hwy 97 to streetName: Cariboo and streetType: Hwy in locality: 70 Mile House

Also, apply streetName mappings before dropping streetDirections

---

CARIBOO HWY 97 => Hwy 97 in 70 Mile House, 93 Mile House, 100 Mile House, 103 Mile House, 108 Mile House, 141 Mile House, 150 Mile House, Cache Creek, Chasm, Clinton, Lac La Hache, Quesnel, Ashcroft, Maiden Creek

Drop streetDirection for Hwy 97 in Lac La Hache

CARIBOO HWY 97C => Cariboo Hwy in 150 Mile House

AGASSIZ-ROSEDALE HIGHWAY NO 9 => Hwy 9 in Agassiz, Popkum 

CHILCOTIN HWY 20   => Hwy 20 in Alexis Creek, Anahim Lake, Chilanko Forks, Hanceville, Kleena Kleen, Redstone, Riske Creek, Tatla Lake, Williams Lake, Nimpo Lake

YELLOWHEAD HWY => Hwy 5 in Avola, Barriere, Birch Island, Blackpool, Black Pines, Blue River, Chinook Cove, Chu Chua, Clearwater, Darfield, Little Fort, Louis Creek 

Drop streetDirection for Hwy 5 in Avola, Barriere, Birch Island, Blackpool, Black Pines, Blue River, Chinook Cove, Chu Chua, Clearwater, Darfield, Little Fort, Louis Creek

MACKENZIE HWY 20  => HWY 20 in Firvale, Hagensborg, Stuie, Bella Coola

HIGHWAY 97  => Hwy 97 in Fort St John, Lake Country, Maiden Creek, McLeese Lake, Penticton,  Summerland, Sundance Lakes, Arras, Attachie, Groundbirch, Kersley, Kilkerran, Mt Le Moray, Peachland, Progress

Drop streetDirection for Hwy 97 in Alexandria, Arras, Attachie, Australian, Cinema, Groundbirch, Kersley, Kilkerran, Peachland, Progress

HIGHWAY 97 => Alaska Hwy in Fort St John

Drop streetDirection for Hwy 97 in Fort St John

HIGHWAY 97 => John Hart Hwy in Hasler Flats

Drop streetDirection for John Hart Hwy in Hasler Flats

SEA TO SKY HWY => Hwy 99 in Pavilion

HIGHWAY 99 => Hwy 99 in RD Pemberton

HIGHWAY 93 95  => Hwy 93 and 95 in Fairmont Hot Springs, Fort Steele, Windermere, Athalmer, Canal Flats, Skookumchuck, Spillimacheen

HIGHWAY 3 93  => Hwy 3 and 93 in Galloway, Fort Steele, Jaffray

HIGHWAY 3 95 => Hwy 3 and 95 in Cranbrook, Moyie, Radium Hot Springs

HIGHWAY 3 => Hwy 3 in Creston
Drop streetDirection for Hwy 3 in Creston

HIGHWAY 7 => Hwy 97 in Dease Lake

HIGHWAY 16 => McBride Hwy 16 in Dunster

HIGHWAY 16 => Prince George Hwy 16 in Ferndale-Tibor, Perden

HIGHWAY 23 => Hwy 23 in Nakusp

Drop streetDirection for Hwy 23 in Nakusp

MERRITT PRINCETON HWY => MERRITT PRINCETON HWY 5A in Aspen Grove 

PRINCETON KAML HWY => HWY 5 in Kamloops (?)

Highway 10 (56 Ave)=> 56 Ave in Surrey
Highway 10 (58 Ave)=> 58 Ave in Surrey

**Comment by mraross** [comment]
No hwy 97 addresses coming up in 93 Mile House

**Comment by gleeming** [comment]
Here's a record from BC Assessment that falls in the 93 Mile House ITN locality:

2016,24,Cariboo,727,Williams Lake Rural (727),45413310,6721 CARIBOO HWY 97 S 100 MILE HOUSE,,6721,,CARIBOO HWY 97,,S,100 MILE HOUSE

Street name mapping as per this ticked has been applied and the geocode input record becomes:
396535,Hwy 97 S 93 Mile House BC,,,,,6721,,,,,93 Mile House,BC,,72745413310,396535,BCA,1171774,parcelPoint,high,A,,1324528,742039,396535,CAP,Y,"",medium,A,,,,N

The highway through 93 Mile House in ITN is called Hwy 97 not Hwy 97 S so all of the BCA addresses in this locality get rejected.

**Comment by mraross** [comment]
CARIBOO HWY 97 70 mile house doesn't return hwy 97, 70 mile house

**Comment by mraross** [comment]
Verified in test.
