### ISSUE TITLE
Post Geocoder developer guide to BC DevHub

### ISSUE THREAD

**Issue by BK01** [bcgov/api-specs#360]
**Outcome:**
Post the existing [Geocoder developer guide](https://github.com/bcgov/api-specs/blob/master/geocoder/geocoder-developer-guide.md) on [DevHub](https://developer.gov.bc.ca/).

**Tasks:**
1. Add [front matter](https://developer.gov.bc.ca/devhub-app-web/Z2bHTug) to the existing Geocoder developer guide in [bcgov/api-specs](https://github.com/bcgov/api-specs/tree/master/geocoder)

------- https://github.com/bcgov/api-specs/pull/370/files

2. Fork registry.yaml, create a Location Services collection, submit a PR, review by DevHub team

**Comment by mraross** [comment]
Now in JIRA
