### ISSUE TITLE
Unable to read geometry

### ISSUE THREAD

**Issue by BK01** [bcgov/api-specs#37]
Client is having issues creating a Geomark using a shapefile. 

Initial review of the shapefile properties do not reveal any errors. Geometry checks are successful and the number of vertices is only 11,000 which is well within the 20,000 limit. File size is also only 194 KB.

We receive the following error message on screen.

"The Application you are looking for is down, please report to the Application Manager."

Within the app logs we then see this message:

2016-08-24 14:49:20,788ERRORca.bc.gov.geomark.web.rest.GeomarkUnable to read geometry
com.revolsys.util.WrappedException: com.ctc.wstx.exc.WstxEOFException: Unexpected EOF in prolog  at [row,col {unknown-source}]: [1,0]

Repeating the test today resulted in the following message:

Caused by: com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character 'f' (code 102) in prolog; expected '<'
 at [row,col {unknown-source}]: [1,1]

**Comment by BK01** [comment]
Update: This issue is now confirmed to be occurring in all three environments.

**Comment by pauldaustin** [comment]
Please include the steps to repeat the problem. Including the shapefile that has the error. Indicate if the client is using the web browser or the Java API.

**Comment by pauldaustin** [comment]
Brian,

Looks like this was user error. For Shapefile the XML reading code that caused that error would never be used. My prediction is that the user didn't select the correct File Format and specified something like the KML file format instead if shpz or shp.

**Comment by BK01** [comment]
Issue resolved in Geomark version 5.0.1 (DLV). Tested in Chrome on Dec 9, 2016 using both shp and shpz.
