### ISSUE TITLE
https server 500 error in response to sites/nearest.geojson request

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#372]
https://geocoder.api.gov.bc.ca/sites/nearest.geojson?locationDescriptor=accessPoint&maxDistance=5000&excludeUnits=true&onlyCivic=true&brief=true&point=-127.28111966701108,49.65348852775016

**Comment by cmhodgson** [comment]
The error handler was not setup to handle geojson output (even though it is the same actual output as json). Had to add the geojson mime type to the ErrorMessageConverter's supported types. This is fixed locally and ready for future delivery.

**Comment by mraross** [comment]
Issue moved to [bcgov/ols-geocoder #34](https://github.com/bcgov/ols-geocoder/issues/34) via [**ZenHub**](https://www.zenhub.com/)
