### ISSUE TITLE
In address finder widget page, doc section, jquery url is incorrect

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#38]
Current url is:
https://code.jquery.com/jquery-1.9.1.min.js

@ll911  needs to know what the correct url and version is?

**Comment by cmhodgson** [comment]
Sorry I'm not sure what is wrong? That URL works for me, it is hosted by MaxCDN, it is the file referenced in both the docs and used in the code for the widget itself, which is working for me on my desktop before I committed it.

**Comment by cmhodgson** [comment]
Still waiting for an explanation of what is actually wrong here?

**Comment by ll911** [comment]
@mraross new version is correct, reference in current prod is wrong.

**Comment by mraross** [comment]
Temporary new homes

http://geocoder-devkit.pathfinder.gov.bc.ca/widget/ 
http://geocoder-devkit.pathfinder.gov.bc.ca/ale/ 
http://geocoder-devkit.pathfinder.gov.bc.ca/als/

**Comment by cmhodgson** [comment]
We agreed to not try to patch prod, the error is a missing /lib/ in the path which I think many people would figure out by looking at the source code for the page. The new code.jquery url works and is CDN hosted and is in place in the delivery devkit widget page.
