### ISSUE TITLE
Add Geomark to Group

### ISSUE THREAD

**Issue by BK01** [bcgov/api-specs#381]
When attempting to add a Geomark to a group (in DLV) the following error message is received.

HTTP ERROR 404

This apps.gov.bc.ca page can’t be found

No webpage was found for the web address:https://apps.gov.bc.ca/pub/geomark/secure/admin/geomarkGroups/<ACTUAL GEOMARK ID REMOVED FOR THIS ISSUE SUMMARY>

**Comment by pauldaustin** [comment]
This issue doesn't make sense as the URL is for production but the comment says it's the DLV environment

**Comment by BK01** [comment]
Resolved in 6.0.0-SNAPSHOT

**Comment by BK01** [comment]
Correct behaviour verified in DLV
