### ISSUE TITLE
Geomark KML placemark balloon

### ISSUE THREAD

**Issue by BK01** [bcgov/api-specs#383]
When the error handling successfully prevents a user from creating a Geomark (based on user error), and displays the appropriate error message, the 'Create geomark' header disappears at the top of the placemark balloon.

**Comment by pauldaustin** [comment]
Added Create Geomark heading on the error page. I also noticed that some styles were causing extra whitespace at the top of the ballon, so I've added an override style to remove that whitespace (padding).

**Comment by BK01** [comment]
Correct behaviour verified in DLV (6.0.0-SNAOSHOT)
