### ISSUE TITLE
Geomark groups page - Error message

### ISSUE THREAD

**Issue by BK01** [bcgov/api-specs#385]
When initially loading the Geomark groups page we receive the following error message as a pop message.

The message describes a 'DataTables warning - Ajax error' with a provided table ID.

**Comment by pauldaustin** [comment]
@bk01 I think this is already fixed in the 6.0.0-SNAPSHOT that is in delivery

**Comment by BK01** [comment]
Confirmed. Resolved in 6.0.0-SNAPSHOT

**Comment by BK01** [comment]
Correct behaviour verified in DLV.
