### ISSUE TITLE
Link Updates

### ISSUE THREAD

**Issue by BK01** [bcgov/api-specs#393]
1.
**Page:** http://apps.gov.bc.ca/pub/geomark/docs/
**Link**: Java (6+) download link is broken

2.
**Page:**http://apps.gov.bc.ca/pub/geomark/geomarks#geomarks
**Link**:  For 'Geomark URLs' label link
Change from: https://github.com/bcgov/api-specs/blob/master/geomark/glossary.md#geometryUrl
To instead be: https://github.com/bcgov/api-specs/blob/master/geomark/glossary.md#geomarkURL

3.
**Page**: http://apps.gov.bc.ca/pub/geomark/geomarks
**Link**: Update the following link to use a permalink.
 "Click [here](http://www2.gov.bc.ca/gov/content/governments/about-the-bc-government/databc/geographic-data-and-services/geomark-webservice) for complete information on the service"
https://www2.gov.bc.ca/gov/content?id=F6BAF45131954020BCFD2EBCC456F084

**Comment by BK01** [comment]
Link number 2 value was updated in Geomark Admin. Will re-test after restart.

**Comment by pauldaustin** [comment]
1. Updated in next release

**Comment by pauldaustin** [comment]
2. updated in next release

**Comment by pauldaustin** [comment]
3. I have also changed those links into the  default config of the app

**Comment by BK01** [comment]
Correct behaviour verified in DLV (6.0.0-SNAPSHOT)

**Comment by BK01** [comment]
1 - Cannot validate yet as Developer API docs icon is no longer in page header
2 - Validated in DLV (6.0.0 SNAPSHOT)
3 - Validated in DLV (6.0.0 SNAPSHOT)

**Comment by bolyachevets** [comment]
1 - to quote Paul:
"The docs got removed from the app as part of the pre-work for open sourcing and hosting of the code on github.com. Bundling the docs in the app was a main to maintain. Have a look in the .github/workflows/maven.xml. See the last section #### Github Pages ####. That pushes the changes to the gh-pages branch whenever you commit.
 
You can see what it looks like here. That URL will go away when you take over maintenance of the app. However if you create a github repo for Geomark and push changes to it then it will auto deploy the docs to a similar URL to below.
 
https://pauldaustin.github.io/geomark/"
