### ISSUE TITLE
OGC Geopackage format

### ISSUE THREAD

**Issue by BK01** [bcgov/api-specs#399]
Implement OGC GeoPackage as a supported data exchange format for the Geomark Web Service

**Comment by BK01** [comment]
The GeoPackage format is listed in the downloadable file format drop-down list but does not download when selected in DLV.

**Comment by pauldaustin** [comment]
Fixed, it was an issue with auto commit and transactions

**Comment by BK01** [comment]
DLV UAT results:

Create and View (GeoPackage):
- Geomarks were created in Google Earth and downloaded in GeoPackage (gpkg) format
- GeoPackage file can be loaded in ArcGIS Pro (features and extent recognized) and symbolized using WGS84.
- Downloaded GeoPackage files referenced above cannot be used to Create a Geomark from file (500 error)

**Comment by pauldaustin** [comment]
The GeoPackage needed to be copied to a file on the server and then opened from there. Unfortunately that didn't work from the InputStream on the HTTP Request. The is because it didn't have a filename. So I wrapped it in an InputStreamResource.

**Comment by BK01** [comment]
Validated in DLV with version 6.0
