### ISSUE TITLE
in non-civic address prep script, use occupant's DESCRIPTION property to populate site.accessPoint.narrativeLocation

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#40]

**Comment by gleeming** [comment]
The field from the GSR export is called DESCRIPTION and is now getting mapped to narrative location for NCAPs

**Comment by gleeming** [comment]
Scripts updated in the 3.0.0 deployment.  It will not be able to be verified until the next data processing run is completed.

**Comment by mraross** [comment]
Can this be verified now?

**Comment by gleeming** [comment]
It should be once Brian finishes the data processing and loads it into a geocoder.
