### ISSUE TITLE
Geomark docs - GitHub vs. App location

### ISSUE THREAD

**Issue by BK01** [bcgov/api-specs#420]
The question mark icons in the Geomark application UI direct users to a GitHub repo instead of the application docs at apps.gov.bc.ca.

**Comment by bolyachevets** [comment]
I believe Paul explained the issue with docs earlier:

"The docs got removed from the app as part of the pre-work for open sourcing and hosting of the code on github.com. Bundling the docs in the app was a main to maintain. Have a look in the .github/workflows/maven.xml. See the last section #### Github Pages ####. That pushes the changes to the gh-pages branch whenever you commit.
 
You can see what it looks like here. That URL will go away when you take over maintenance of the app. However if you create a github repo for Geomark and push changes to it then it will auto deploy the docs to a similar URL to below.
 
https://pauldaustin.github.io/geomark/
 
In the Geomarks.json config file you can add additional footer links as shown below
 
"footerLinks": {
    "About gov.bc.ca": "http://www2.gov.bc.ca/gov/content/about-gov-bc-ca",
    "Disclaimer":"http://www2.gov.bc.ca/gov/content/home/disclaimer",
    "Privacy":"http://www2.gov.bc.ca/gov/content/home/privacy",
    "Accessibility":"http://www2.gov.bc.ca/gov/content/home/accessibility",
    "Copyright":"http://www2.gov.bc.ca/gov/content/home/copyright",
    "Contact Us":"http://www2.gov.bc.ca/gov/content/home/contact-us"
  },
 "

**Comment by bolyachevets** [comment]
I moved the geomark dlv docs url to gh-pages: https://bcgov.github.io/ols-devkit/geomark/docs/
So for now, the "i" info icons redirect to that url as root.
