### ISSUE TITLE
GeoJson coordinate formats

### ISSUE THREAD

**Issue by bolyachevets** [bcgov/api-specs#423]
Download options for GeoJson allow user to pick only one type of coordinate system: 4326
<img width="1351" alt="Screen Shot 2021-12-06 at 2 46 34 PM" src="https://user-images.githubusercontent.com/22973013/144935223-c1345173-3c66-4210-9743-45faff014f72.png">

**Comment by pauldaustin** [comment]
Yes GeoJson itself only supports 4326

https://datatracker.ietf.org/doc/html/rfc7946#section-4

The old spec allowed for different coordinate systems, but the one that became a standard doesn't
