### ISSUE TITLE
Route planner: handle passenger ferry ITN line type

### ISSUE THREAD

**Issue by gleeming** [bcgov/api-specs#43]
Accommodate the new ITN transport line type for passenger ferry (FP) in the enumeration.  Also add a filter to ignore all passenger ferry edges in the network build.

**Comment by mraross** [comment]
Confirmed in Test with the following query:

https://routertst.api.gov.bc.ca/route.kml?routeDescription=Trip%20to%20an%20island%20with%20only%20a%20passenger%20ferry&points=-123.707942%2C48.778691%2C-123.9255472245603%2C49.17704747833908&outputSRS=4326&criteria=shortest&distanceUnit=km&apikey=a82472ff8f754968b4e70943adc63888

**Comment by BK01** [comment]
Tested in DLV with the following query - Oct 22, 2016:

https://routerdlv.api.gov.bc.ca/route.html?routeDescription=shortest%20distance%20in%20km%20and%20html&points=-123.403773%2C48.646319%2C-123.073075%2C49.086373&outputSRS=4326&criteria=shortest&distanceUnit=km&apikey=a82472ff8f754968b4e70943adc63888
