### ISSUE TITLE
Router planner: change startup to operate against individual GeoJSON inputs

### ISSUE THREAD

**Issue by gleeming** [bcgov/api-specs#44]
There are new street load file conventions created for geocoder v2.1.  Modify startup to accommodate the individual inputs now available instead of the old street_load_other.json which is being deprecated.  Also it might be prudent to allow the router to work off of street_load_street_segments.json (note the file name may have changed) and have a fall back to street_load_street_segments_post.json

**Comment by mraross** [comment]
Confirmed in Test

**Comment by BK01** [comment]
Verified in TEST migration on Oct 21, 2016
