### ISSUE TITLE
Cannot detect street name alias faults for Site-Name-based Matches

### ISSUE THREAD

**Issue by cmhodgson** [bcgov/api-specs#45]
This is particularly a problem for street-named based NCAPs such as the test data "Weigh Scale -- Patricia Bay Hwy, Saanich, BC". When searched using the alias hwy 17, it is returned but with a streetName.notMatched fault. Fixing this requires adding a list of aliasNames to every segment (right now they only store their primary names).

**Comment by cmhodgson** [comment]
Adding a list of aliasNames to every segment didn't seem to cause a significant increase in memory usage overall.

**Comment by cmhodgson** [comment]
Confirmed working in delivery:
http://delivery.apps.gov.bc.ca/pub/geocoder/addresses.html?addressString=Weigh%20Scale%20--%20Hwy%2017,%20Saanich,%20BC

**Comment by mraross** [comment]
Verified in delivery with request above
