### ISSUE TITLE
Geocoder fails to handle 1/2 addresses

### ISSUE THREAD

**Issue by pramsey** [bcgov/api-specs#46]
http://apps.gov.bc.ca/pub/geocoder/addresses.geojson?addressString=535%C2%BD%20Fisgard%20Street%2C%20Victoria%2C%20BC

535½ Fisgard Street, Victoria, BC

The 1/2 address component is lost in the response.

**Comment by mraross** [comment]
It failed because the UTF-8 character for  "1/2" was used and there was no space between civic number and fraction. Use the three characters 1/2 with a space between civic number and fraction as in:

 535 1/2 Fisgard Street, Victoria, BC

**Comment by pramsey** [comment]
The data in question were sourced from a BC gov't agency, so it's not just my caprice :) thanks for the extra usage note.
