### ISSUE TITLE
In geocoder/addresses, add support for fraction character one-half

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#47]
Allow UTF-8 fraction character one-half (e.g., ½) in a civic number prefix in addressString or civicNumberSuffix input parameters. Output of fractions should not be changed (e.g., "1/2", not ½) as per Canada Post standard.

**Comment by cmhodgson** [comment]
test url: http://delivery.apps.gov.bc.ca/pub/geocoder/addresses.html?addressString=535%C2%BD%20Fisgard%20Street%2C%20Victoria%2C%20BC

**Comment by mraross** [comment]
Verified in delivery

**Comment by mraross** [comment]
verified in test
