### ISSUE TITLE
XHTML Output Restyle

### ISSUE THREAD

**Issue by cmhodgson** [bcgov/api-specs#49]
The current XHTML output is no longer appropriate. It should be changed by:
- remove sidebar menu
- add gov header/footer using leo's javascript widget
- add some css styling to make it a bit more readable

**Comment by cmhodgson** [comment]
The unipear script wasn't working because of CSP security. Even after fixing that, it still doesn't seem to be adding the header and footer.

**Comment by ll911** [comment]
Why xhtml? Should be using stand HTML as unipear based on embedded JavaScript

Sent from my iPhone

On Sep 16, 2016, at 6:23 PM, Michael Ross <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #49<https://github.com/bcgov/api-specs/issues/49> to @ll911<https://github.com/ll911>.

-

**Comment by mraross** [comment]
If the mime type is changed to HTML, will the unipear headers/footers service calls work?

**Comment by ll911** [comment]
xhtml is treated like xml, not the mime type, but the content type

Sent from my iPhone

On Sep 16, 2016, at 6:32 PM, Michael Ross <notifications@github.com<mailto:notifications@github.com>> wrote:


If the mime type is changed to HTML, will the unipear headers/footers service calls work?

-

**Comment by mraross** [comment]
Understood. So if we change the format to HTML, will the headers/footers come out?

**Comment by ll911** [comment]
If the html is created correctly.

Sent from my iPhone

On Sep 16, 2016, at 6:37 PM, Michael Ross <notifications@github.com<mailto:notifications@github.com>> wrote:


Understood. So if we change the format to HTML, will the headers/footers come out?

-

**Comment by mraross** [comment]
Chris: Looks like we need to go to HTML to get the headers/footers coming out. I guess it means flipping the roles of HTML and XHTML formats to display and data. Can you please estimate this work?

**Comment by cmhodgson** [comment]
After a discussion on the phone we agreed that the headers were not necessary for the (x)html output. The html output remains as it was, plain and unstyled, and the xhtml output now has some minor table styling to enhance readability.

**Comment by cmhodgson** [comment]
Confirmed in delivery.

**Comment by mraross** [comment]
Verified in delivery.

**Comment by mraross** [comment]
verified in test
