### ISSUE TITLE
RangeGen outputs subsites for sites that were dropped

### ISSUE THREAD

**Issue by cmhodgson** [bcgov/api-specs#50]
The range generator currently passes all subsites through, we need to drop subsites of sites which are dropped by the range generator for any reason (typically too far from nearest segment with the given name).

**Comment by cmhodgson** [comment]
This is done. Will require re-processed data to test.

**Comment by cmhodgson** [comment]
Not really any way for this to be tested through the API.

**Comment by mraross** [comment]
Verified
