### ISSUE TITLE
Update Geocoder data prep README file

### ISSUE THREAD

**Issue by cmhodgson** [bcgov/api-specs#54]
We have a beautiful diagram that is now woefully out of date. lets fix that. Will be useful for training DA's on the process.

**Comment by gleeming** [comment]
Updated to reflect 3.0.0 and some future (dashed) possibilities.

https://docs.google.com/drawings/d/1rduJHuNeH4ZKlb5Wx1Rn48AeQ-krys4ZFsPiebgyKSY/edit
