### ISSUE TITLE
Occupant Search for NCAP-based occupant returns site match

### ISSUE THREAD

**Issue by cmhodgson** [bcgov/api-specs#55]
Searching for Golden Spruce Tree Trail (or any other NCAP-occupant) returns the SITE match instead of the OCCUPANT:

http://delivery.apps.gov.bc.ca/pub/geocoder/occupants/addresses.html?addressString=Golden%20Spruce%20Tree%20Trail%20--%20Port%20Clements,%20BC

The OCCUPANT match IS there, and can be found by adding &matchPrecisionNot=SITE

http://delivery.apps.gov.bc.ca/pub/geocoder/occupants/addresses.html?addressString=Golden%20Spruce%20Tree%20Trail%20--%20Port%20Clements,%20BC&matchPrecisionNot=SITE

Part of the problem is that that SITE name index is searched first, and so the "perfect" match is found and short-circuited out. Even if a maxResults >1  is provided, avoiding the short-circuit, the OCCUPANT match has the same name and location as the SITE so it is considered to be a duplicate match and because they both have the same score, either could be selected to be included in the list of results.

**Comment by mraross** [comment]
Can we set matchPrecisionNot to SITE by default for occupants/addresses queries?

**Comment by cmhodgson** [comment]
We can; the downside is then you will not get ANY site matches, so if you search for "Royal Jubilee Hospital --" as an occupant with the data we have now, you would not find it. Another alternative is the set matchPrecision=OCCUPANT and ONLY return occupants; if that is the intent.

**Comment by cmhodgson** [comment]
Over a phone conversation we decided that we should default set matchPrecision=OCCUPANT for occupant queries, so that by default ONLY occupant matches will be returned.

**Comment by cmhodgson** [comment]
Confirmed fixed in delivery.

**Comment by mraross** [comment]
Verified in delivery
