### ISSUE TITLE
avoid 404 in site root

### ISSUE THREAD

**Issue by ll911** [bcgov/api-specs#57]
$SITE_DOMAIN/pub/geocoder/ is getting 404 error, can you add redirect like 

``` jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<%
response.setStatus(301);
response.setHeader( "Location", "$BCDC_URL or $API_CONSOLE URL");
response.setHeader( "Connection", "close" );
%>
```

see sample like http://delivery.apps.gov.bc.ca/pub/geocoder

**Comment by cmhodgson** [comment]
Redirect is working in delivery:
http://delivery.apps.gov.bc.ca/pub/geocoder/

**Comment by mraross** [comment]
Verified in delivery

**Comment by ll911** [comment]
@cmhodgson @mraross I added those lines as index.jsp in delivery, that's why delivery redirect works, @cmhodgson can you add it to the source? @mraross can you confirm what's the redirect should go to? `$BCDC_URL or $API_CONSOLE URL` it's set to API CONSOLE at the moment in delivery.

**Comment by cmhodgson** [comment]
I've redepolyed to delivery; there is no more index.jsp or any jsp handling at all. The redirect is done in the controller.

**Comment by ll911** [comment]
Even better.

Sent from my iPhone

On Sep 20, 2016, at 12:28 PM, Chris Hodgson <notifications@github.com<mailto:notifications@github.com>> wrote:


I've redepolyed to delivery; there is no more index.jsp or any jsp handling at all. The redirect is done in the controller.

-
