### ISSUE TITLE
in geocoder/addresses, Hwy 1, 5, 9, 16, 37, 93, 95, 97 return localities where the highway doesn't go through

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#58]
In the results to the test query below, there are numerous localities that are not on Hwy 97 such as:
Port Hardy, Gold River, Duncan, and Campbell River.
Prince Rupert, Smithers, Fraser Lake

Test query:
http://delivery.apps.gov.bc.ca/pub/geocoder/addresses.kml?addressString=hwy+97&maxResults=50

**Comment by mraross** [comment]
Other highways similarly affected include 1, 5, 9, 16, 37, 93, and 95

**Comment by mraross** [comment]
Hwy 37
Parksville, Stui, Surrey

http://delivery.apps.gov.bc.ca/pub/geocoder/addresses.kml?addressString=hwy+37&maxResults=100

**Comment by mraross** [comment]
Hwy 16
Summerland, Woss, Kinanskan

Test query:
http://delivery.apps.gov.bc.ca/pub/geocoder/addresses.kml?addressString=hwy+16&maxResults=100

**Comment by gleeming** [comment]
This appears to be an issue with how highway aliases were generated for ticket #34.  It only affects street precision matches and the data in the locality centroids table.

**Comment by gleeming** [comment]
Reworked the street prep flow to properly accommodate segment/name type aliases in the locality centroid layer (previously we only supported name->name aliases).  Also made locality centroid calculations/workflow more efficient so the script runs much faster.

**Comment by mraross** [comment]
Verified in delivery with the following query:

http://delivery.apps.gov.bc.ca/pub/geocoder/addresses.kml?addressString=hwy+97&maxResults=50&minScore=67

**Comment by mraross** [comment]
Verified in test
