### ISSUE TITLE
Auto generate localities where HWY 97 doesn't have street directions

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#67]
Graham to generate a spreadsheet of in the form required by the address prep scripts. Michael to review and send back to Graham who will then integrate the locality list into the address prep scripts.

**Comment by gleeming** [comment]
Here' the initial query I used:
SELECT name_full AS itn_primary_name, hwy_rte, city_left AS locality, count(*) FROM dfar_road_segment dfar
LEFT JOIN structured_name sn ON sn.structured_name_id = dfar.name_id
WHERE (hwy_rte IS NOT NULL AND hwy_rte != '')
AND (name_full LIKE '%Hwy%' OR prefix_name_direction_code = 'HWY' OR suffix_name_direction_code = 'HWY')
AND name_descriptor_code IS NULL
AND name_full NOT LIKE '% Frtg%'
AND name_full NOT LIKE '% Frontage%'
AND name_full NOT LIKE '% Conn%'
AND name_full NOT LIKE '% Access%'
GROUP BY name_full, hwy_rte, city_left
ORDER BY name_full, city_left, hwy_rte;

**Comment by mraross** [comment]
Rather than drop streetDirection for localities that have undivided highway, drop streetDirection for localities that don't have divided highways since they are only a handful of localities with divided highways. If a given locality has both divided and undivided highway, don't drop any streetDirections in that locality.

**Comment by mraross** [comment]
Replaced by new strategy based on hwy direction missing fault with zero penalty
