### ISSUE TITLE
Prevent U-turns in divided intersections

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#69]
in router, generated route can contain a U-turn in a divided intersection. U-turns are not allowed in intersections.
Detail  Start: 988 Topaz Ave, Victoria, BC -123.360677,48.442561
End: 710 Redbrick St, Victoria, BC -123.368386,48.444587

https://routertst.api.gov.bc.c/router/tst/route.kml?points=-123.360677%2C48.442561%2C-123.368386%2C48.444587&outputSRS=4326&criteria=shortest&distanceUnits=km&apikey=yourApiKey

**Comment by cmhodgson** [comment]
This is a duplicate of #101

**Comment by mraross** [comment]
duplicate of 101
