### ISSUE TITLE
in occupant prep script, revise set of fields to import from GSR export CSV file

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#7]
1. Drop SOURCE_DATA_ID
2. Drop CUSTODIAN_ID
3. Add CUSTODIAN_ORG_DESCRIPTION

**Comment by gleeming** [comment]
Removed the first two fields from the occupants_vw_Load.csv file ; the CUSTODIAN_ORG_DESCRIPTION was never present.  Assigning to Chris to make changes to the geocoder app that loads this data layer.

**Comment by cmhodgson** [comment]
Removed from the reading, storage, and output formats.

**Comment by gleeming** [comment]
I misread the 3rd item as a drop.  CUSTODIAN_ORG_DESCRIPTION is now the last field in the CSV file, so it will have to be included in the geocoder.  I assume this means adding a field to hold this info in all the output formats.

**Comment by mraross** [comment]
Actually, we don’t need to include it in what geocoder users see. Its just for your GSR processing scripts.

**Comment by cmhodgson** [comment]
Here is an example test occupant url:
http://delivery.apps.gov.bc.ca/pub/geocoder/occupants/addresses.html?addressString=MASSET%20PROVINCIAL%20--%201666%20Orr%20St,%20Masset,%20BC

**Comment by mraross** [comment]
Verified in delivery
