### ISSUE TITLE
In route planner/directions, add an includeBridges parameter that controls presence of bridges and tunnels in directions

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#71]
Add a includeBridges parameter that, if true, directions for crossing every bridge or tunnel are included in the route. If false (default), bridge crossings are excluded. This will substantially shorten the number of directions in routes. For example, when includeBridges=false the following directions would be included in the route from Vancouver to Prince Rupert:
```
Continue onto Hwy 16 for X km
```
When includeBridges=true all bridge crossing would be included in directions:
```
Continue onto Hwy 16 for 21 km
Continue onto Prince Creek Bridge for 35 m
Continue onto Hwy 16 for 4.4 km
Continue onto Boulder Creek Bridge for 60 m
Continue onto Hwy 16 for 13 km
Continue onto Coyote Creek Bridge for 20 m
Continue onto Hwy 16 for 25 km
Continue onto Big Oliver Creek Bridge for 55 m
Continue onto Hwy 16 for 1.5 km
Continue onto Little Oliver Creek Bridge for 50 m
Continue onto Hwy 16 for 6.1 km
Continue onto Legate Creek Bridge for 80 m
Continue onto Hwy 16 for 7.7 km
Continue onto Saint Croix Creek Bridge for 40 m
Continue onto Hwy 16 for 5.6 km
Continue onto Chimdemash Creek Bridge for 75 m
Continue onto Hwy 16 for 8.2 km
Continue onto Kleanza Creek Bridge for 80 m
Continue onto Hwy 16 for 8.2 km
Continue onto Copper River Bridge for 150 m
Continue onto Hwy 16 for 6.9 km
Continue onto Dudley Little Main Bridge for 400 m
Continue onto Hwy 16 for 350 m
Continue onto Dudley Little Bridge for 250 m
Continue onto Hwy 16 for 400 m
```

Another approach is to add an ignoreHighwayNameChanges boolean input parameter. If true, directions don't break when the street name of the same highway route changes and the official street name is not a municipality street name. For example, a route that goes from yates and douglas st in victoria to Goldstream park will have one direction on Douglas St then one direction on Hwy 1 starting at Carey Rd and Hwy 1.

**Comment by cmhodgson** [comment]
The direction "continue on <new street name>" is standard in every navigation system I have used. However I understand this may be a requirement for onRoute to reduce the size of the directions, as they are being used as a legal description of the permitted route. In order to do this, we will need to add the route number to the street data as it is not included presently. We may need to be careful of exit ramps which include the route number - or perhaps exit/entrance ramps could also be removed from this shortened description? Perhaps a parameter "directions=minimal" or "directions=turnsOnly".

**Comment by mraross** [comment]
How about just not breaking on bridges. In other words if the name of a road segment before and after a bridge is the same, don't break the directions.

**Comment by mraross** [comment]
Issue moved to [bcgov/ols-router #12](https://github.com/bcgov/ols-router/issues/12) via [**ZenHub**](https://www.zenhub.com/)
