### ISSUE TITLE
Can't edit a locality mapping

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#78]
source and target name fields are not editable. Only confidence.

https://delivery.apps.gov.bc.ca/ext/sgw/geocoderadmin/loc_maps_edit.jsp

**Comment by cmhodgson** [comment]
In Cassandra we cannot change primary key fields, so only the confidence is editable. It would be possible to make the edit page delete and create a new mapping, but I felt that the admin user could just as easily do that themselves.

**Comment by mraross** [comment]
Verified
