### ISSUE TITLE
There are only six addresses for Atlin

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#79]
7271 1st St, Atlin, BC
221 Green St, Atlin, BC
256 McBride Blvd, Atlin, BC
39 1st St, Atlin, BC
130 2nd St, Atlin, BC
137 1st St, Atlin, BC

Was there no data in BCA and ABC or was the data bad, or is there a script issue?

**Comment by gleeming** [comment]
No ABC, and 874 of BCA's records have either no street number or geometry.  Of 18 remaining candidates, only 13 were site-worthy.

**Comment by mraross** [comment]
Verified
