### ISSUE TITLE
in batch geocoder, request for CSV and EPSG 4326 coordinates returns EPSG 3005 instead

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#80]
Submit a csv file of addresses and request CSV output in resultSrid=4326. The resulting CSV file will be in EPSG 3005 instead.  I tested a similary query with the CPF Map Tile By Location plugin and it gave results in the correct projection so it looks like the Batch Geocoder plugin, not CPF

**Comment by mraross** [comment]
Doesn't honour 26911 either. Probably a CPF problem after all.

**Comment by cmhodgson** [comment]
I have no control over output projection in CPF. Paul Has identified this as a CPF problem.

**Comment by mraross** [comment]
verified
