### ISSUE TITLE
Geocoder emits invalid JSON when query includes backslash

### ISSUE THREAD

**Issue by pramsey** [bcgov/api-specs#81]
The following query will induce the geocoder to emit an invalid JSON response:

http://apps.gov.bc.ca/pub/geocoder/addresses.geojson?addressString=42700%20Walnut%20Ave%2C%20Chilliwa%5CCk%2C%20BC%2C%20V2R5C2

The \ loops straight through to the output.

**Comment by mraross** [comment]
In the results, the queryAddress contains a backslash but the fullAddress doesn't. This is true for all output formats. I take it the backslash has to be escaped in JSON?

**Comment by pramsey** [comment]
Correct, otherwise it's understood as escaping the character in front of it,  which might not be allowed. My parser says this:

```
pbpaste | json_pp
illegal backslash escape sequence in string, at character offset 43 (before "\\Ck, BC, V2R5C2","s...") at /opt/local/bin/json_pp line 44.
```

**Comment by cmhodgson** [comment]
Of course the results don't include the backslash, it isn't part of the actual matched address. The backslash (and some other characters) do need to be escaped in JSON. I had previously hand-rolled a regex to backslash-escape double-quotes (only), but now I have it using the apache commons JSON string-escape method which should get us valid output regardless of the input.

**Comment by mraross** [comment]
Verified in delivery

**Comment by mraross** [comment]
Verified in Test
