### ISSUE TITLE
In route planner directions, link directions to intersections

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#82]
Submitted on behalf of Peter Spry, MOTI:

'Could you return the directions in a way that would allow the individual directions to be linked to the vertices or line segments of the route? That way it would be possible to show where on the map a particular turn was.'

**Comment by cmhodgson** [comment]
This may need to be handled differently in different output formats.

**Comment by pspry** [comment]
Perhaps add another array containing point or bbox elements that match, one-to-one, the elements of the directions array?

**Comment by cmhodgson** [comment]
I think I would want to break the route linestring up into smaller linestrings that correspond with the directions, and put the direction as an attribute of each linestring. In KML this would allow you to mouseover or click on a segment of route and get the associated direction.

**Comment by pspry** [comment]
that would work too

**Comment by mraross** [comment]
Unfortunately, this will violate the DRA terms of use in that we would be giving out individual block geometries. These are only supposed to be available to non-DRA clients after one year from date of creation or update.

We could include the start and/or end intersection of each direction segment. Intersections are already being distributed by the Geocoder under OGL.

**Comment by pspry** [comment]
If you can provide point locations for Start and End intersections locations for each turn then the client could create an appropriate bounding box to zoom to (or highlight) and you wouldn't be exposing individual segment geometries.

**Comment by mraross** [comment]
We could compute a precise bbox for each direction segment and return that. In KML, it would just be a folder with a <VIEW> element.

**Comment by cmhodgson** [comment]
We would only be giving out block geometries if the route happened to turn at both ends of the block. The same information could be retrieved by asking for the route from 100 to 200 douglas st. In fact this sort of thing is far more in danger of violating the TOU as you can essentially specify the segment you want. Unless you carefully fabricate your routing source and destination, the chances of any of the route "chunks" aligning exactly with a particular single segment is quite low. 

As far as using BBOXes, if they are "precise", then it would essentially be revealing the individual segments. The BBOXes would probably need to be randomly imprecise to prevent the same problem. Even that could be overcome, if someone was actually trying to reverse engineer the block segments using the router.

**Comment by mraross** [comment]
By precise, I mean given two direction leg end points, determine an appropriate eye altitude that includes a certain amount of context around the end points, then compute the resulting bbox.

**Comment by mraross** [comment]
Link each individual direction leg to the first intersection of the leg. The leg text could be linked or a turn icon added and linked.

**Comment by mraross** [comment]
Superceded by  #174
