### ISSUE TITLE
Add rejected GSR records as occupants that occupy sites with non-civic addresses (locality+province)

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#83]
Take all occupants whose addresses were rejected by the geocoder and add them as sites with non-civic addresses consisting of locality and province. Locality can be determined from the lat/lon and ITN locality coverage, and the parcelPoint set to the lat/lon. If display address is empty, copy rejected physical address into display address.

**Comment by gleeming** [comment]
Doing this would require an additional batching and processing step outside of the current data prep stages.  Additionally a means to incorporate the data back into the base files (append? separate sources?) would be required. To support that would probably require a QA step and changes to the geocoder code itself.

**Comment by mraross** [comment]
Not feasible
