### ISSUE TITLE
In occupant prep, compute whether or not an occupant occupies a non-civic address

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#84]
GSR data custodians don't currently manage the NON_CIVIC_IND flag. Since the default is N, 1600 of 5600 occupants were rejected by occupant prep for geocoder v3.0.  Rather than put the burden on them in the future, enhance occupant prep to compute the type of address by batch geocoding and evaluating match quality of each geocoded address as follows:

If matchPrecision is “LOCALITY” or ”STREET” and has no faults or a missing province fault, and any number of zero-penalty faults 
   then occupant has an associated non-civic address
   else occupant has an associated civic address
endif

**Comment by gleeming** [comment]
After implementation, breakdown of the number of case types from the ~September GSR data is as follows:
- insufficient score: 3555  [most of these are from not-in-any-block faults, i.e. CAPs we want to ignore)
- street level match: 13
- locality level match: 453

In the 3.0 release there were only 4 NCAPs, none of which came from the GSR as they were our hand-crafted cases.  With the enhancements of this ticket, we now recover 462 NCAPs directly from the GSR export, e.g. Bull Harbour Water Aerodrome -- Hope Island BC

**Comment by mraross** [comment]
Is GSR import script still expecting a non-civic address indicator flag in the input file or does GSR have to change its export format?

**Comment by gleeming** [comment]
The development version still expects the flag column but ignores it.  It would also be trivial to change the FME input schema if GSR wanted to simplify the export format.

**Comment by mraross** [comment]
Verified
