### ISSUE TITLE
Detect and fault Rural Route <n> as a postal element

### ISSUE THREAD

**Issue by gleeming** [bcgov/api-specs#85]
Example from EBC:
Rural Route 3 1875 Sandstone Dr Penticton, BC

**Comment by mraross** [comment]
We currently detect RR <n> but Rural Route <n> also appears in input addresses and should be detected as well.

**Comment by cmhodgson** [comment]
Done.

**Comment by cmhodgson** [comment]
Confirmed in delivery.

**Comment by mraross** [comment]
Verified in delivery
