### ISSUE TITLE
Make postal address elements a configurable table in geocoder admin app

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#86]
Rather than adding new postal address elements willy-nilly to the web service code, create a table in geocoder admin. Similar to unit designators, some elements can take a number, some can't.

**Comment by cmhodgson** [comment]
I don't think this is a good idea as the postal address elements get compiled into a Regular Expression that is run on every input string, I would hate for someone to add an erroneous postal address element and have it break the regex; programmatically assembling a regex seems dangerous to me. This is not a list that actually changes significantly over time so hard coding it is appropriate.

Basically, the effort required to build and test the code to reliably assemble a giant regex out of a list of possible postal elements (and the UI to enter/edit the list) is disproportionate to the amount of value received, given that this list rarely changes.
