### ISSUE TITLE
Router planner in delivery more than three times as slow as prod

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#87]
Route Planner can't be migrated to prod until this is investigated. Geocoder and CPF will go to prod on Oct 26 as scheduled.

**Comment by mraross** [comment]
https://routerdlv.api.gov.bc.ca/directions.kml?routeDescription=spansProvinceFastest&points=-126.844567%2C49.978503%2C-122.799997%2C58.925305&outputSRS=4326&criteria=fastest&distanceUnit=km&apikey=yourApiKey

takes 3038 ms in delivery and 714 ms in prod

https://routerdlv.api.gov.bc.ca/distance/betweenPairs.json?routeDescription=fastest%20route%20in%20km%20and%20json&outputSRS=4326&criteria=fastest&distanceUnit=km&apikey=yourApiKey&fromPoints=-119.407515%2C49.839604%2C-122.920091%2C49.200637%2C-123.355745%2C48.426206%2C-121.441796%2C49.868330%2C-116.463428%2C49.051341%2C-124.972951%2C49.715181%2C-123.235246%2C49.450354%2C-124.972951%2C49.715181&toPoints=-116.854024%2C49.744483%2C-122.907620%2C49.225588%2C-115.766510%2C49.511239%2C-118.564775%2C52.008646%2C-123.369628%2C48.408923

takes 40000 ms in delivery and 13741 ms in prod

**Comment by cmhodgson** [comment]
The changes made to the router for this latest version only affect the startup of the app, not the run-time in any significant way. The same query takes 500ms on my desktop, with same versions of code and data.

**Comment by mraross** [comment]
Route planner performance in Prod is fine. Delivery platform was the problem.
