### ISSUE TITLE
Add a resource to geocoder API for parcel ids of a given siteID

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#88]
The new workflow for finding the pids associated with a given address is as follows:

1. Make an addresses request to find the siteID of the site associated with a given address.
2. Make a request to https://geocoder.api.gov.bc.ca/parcels/pids/{siteID} to find the list of pids associate with siteID.

The API gateway can control access to the parcels api  so that only api keys from certain Kong user accounts have access.

This enhancement allows us to retire the sid2pid CPF plugin which is not georedundant. Georedundancy enables continuous access to resources even during scheduled software and data upgrades.

**Comment by mraross** [comment]
The API gateway can use the apikey of a request to compute a groupid property and add it to the http header on its way to the geocoder. What should the group that has access to pids be called?

**Comment by cmhodgson** [comment]
Perhaps just "pid_access"? Until/unless we have more permissions requirements, it could just be any non-empty value, because empty means no access, and non-empty means access. If we get to a place where we need to manage multiple different permissions and groups, we should probably make it configurable using the admin interface, in which case we could rename the groups easily if needed for clarity.

**Comment by mraross** [comment]
Working on getting site pids released as OGL so we don't have to worry about security.

**Comment by gleeming** [comment]
On the processing side, we need to also
1) change the site loader prep FMW script to write the sid2jurol file to the geocoder Staging area
2) move the sid2pid generate FMW script into the geocoding script set
3) update readme to reflect changes (i.e. sid2pid processing will be completely integrated as part of the standard geocoder data prep steps)

**Comment by cmhodgson** [comment]
Michael can you please confirm the content of the result of a call to: parcels/identifiers/{siteId} ?
- also, is it plural ("parcels"), or not ("parcel"), as all of our other resources are named in the plural?

The current sid2pid CPF returns two values, the input siteID, and a comma-separated list of the corresponding pids, do we want the same output, exactly? Other geocoder responses include things like version number, execution time, links to the copyright, etc. Would you prefer to include those in the parcel responses, or not? It is actually easier to include them, if that matters, but not if they need to be different, which I guess the copyright/license notice would need to be different?

**Comment by mraross** [comment]
Keep it the same as current output to minimize required changes by existing sid2pid users.

**Comment by mraross** [comment]
And please call the resource https://geocoder.api.gov.bc.ca/parcels/pids/{siteID}

**Comment by cmhodgson** [comment]
My part of this is done.

**Comment by cmhodgson** [comment]
This is confirmed working in delivery:
http://delivery.apps.gov.bc.ca/pub/geocoder/parcels/pids/758dcce9-ab46-45a6-8892-04d978977b16.html
http://delivery.apps.gov.bc.ca/pub/geocoder/parcels/pids/758dcce9-ab46-45a6-8892-04d978977b16.json

**Comment by mraross** [comment]
parcels/pids has to be in a separate package.

**Comment by mraross** [comment]
@ll911

**Comment by cmhodgson** [comment]
This is now locked out until we add some apikeys to the configuration parameter 'parcelKeys'.

**Comment by mraross** [comment]
Verified in Test
