### ISSUE TITLE
In geocoder, add a parcel links property to site responses

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#89]
Now that parcels are available through an OGL license, users should be able to access them from an address.  

sites/{siteID}parcels should return a list of resources (links) that each returns a parcel. Each parcel in the list could have one resource per format (e.g., this link returns the json representation of parcel 1234, this link returns the html representation of parcel 1234)

Required tasks:
1. Get BC Assessment to allow pids to be released under the OGL-BC license. 
2. Create a new sites/{siteID}/parcels resource.
3. Add a parcels link to each site result as in:
   link name: parcels
   link details: https://geocoder.apis.gov.bc.ca/sites/{siteID}/parcels 
                      where {siteID} is the siteID of the given site.

**Comment by cmhodgson** [comment]
I think sites/{siteID}/parcels link should actually return a list of parcels, with the links being in the same format as the url itself is in, rather than a list of lists of every parcel in every format... eg. sites/{siteID}/parcels.html returns a list of parcels/{PID}.html links.

**Comment by mraross** [comment]
Excellent suggestion.

**Comment by cmhodgson** [comment]
Also, what is actually in the parcels/{PID} resource? Does this need to be secured in the same way as the function that adds pids to the sites? If we are already adding pids to the site, do we really need the sites/siteID/parcels resource? Seems like duplication, although we have already recognized that the ability to reduce the number of fields returned would be nice.

**Comment by mraross** [comment]
Perhaps instead of a separate parcels resource, every resource that returns sites could return a single GeoServer query that would return all parcels associated with the site and in the format of the original resource request. For example, sites/id-10304kdifi49d9495r.geojson would include a Geoserver query for related parcels in geojson format.

In terms of security, Leo said the api gateway can support user groups. He just needs to know what we want to call the user group that is allowed access to pids and which users (e.g., apikeys) are in the group.
What user group name do you suggest?

**Comment by cmhodgson** [comment]
That sounds reasonable, I'm not certain all of our formats are supported by geoserver but close enough. The bigger issue with this is that the output of our service becomes reliant on the geoserver service - the server name, service url, layer name, attribute name, attribute values, etc. I guess this is probably ok and we may be able to make most of the geoserver service parameters configurable so that this could be maintainable without a re-delivery/deployment.

**Comment by mraross** [comment]
Issue moved to [bcgov/ols-geocoder #52](https://github.com/bcgov/ols-geocoder/issues/52) via [**ZenHub**](https://www.zenhub.com/)
