### ISSUE TITLE
in geocoder api, change isPrimary to isOfficial for accessPoint

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#93]

**Comment by mraross** [comment]
Leave isPrimary in API input parm list but have it return the value of isOfficial to support legacy apps.

**Comment by cmhodgson** [comment]
Done locally for all output formats, and also the CPF plugin.

**Comment by mraross** [comment]
Batch geocoder overview page in CPF needs to be updated. Currents displays the following in Results table:

isPrimary boolean 	true if this is primary address for site; false otherwise

**Comment by cmhodgson** [comment]
Yes, this was changed as a matter of course. New description string is: "true if this is the official address for site; false otherwise"

**Comment by cmhodgson** [comment]
Confirmed in delivery.

**Comment by mraross** [comment]
Verified in delivery
