### ISSUE TITLE
In geocoder api, add a status of "proposed" to PhysicalStatus enumeration

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#94]

**Comment by cmhodgson** [comment]
Added. This has no effect without a way to load "proposed" sites or accessPoints, and is not externally visible to my knowledge.

**Comment by mraross** [comment]
Doesn't the batch geocoder plugin config have to change to reflect the new status value?

From this:

  siteStatus  object  (e.g., active, retired)

to this:

  siteStatus  object  (e.g., proposed, active, retired)

**Comment by cmhodgson** [comment]
I've now changed the  description string to "(e.g., proposed, active, retired)" as well.

**Comment by cmhodgson** [comment]
Confirmed in delivery ( you can see it listed on CPF Batch Geocoder overview page).
