### ISSUE TITLE
in Route Planner, directions seem to alternate between local highway name and route number for no apparent reason.

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#95]
Example on Hwy 97 between the Alaska border and the middle of nowhere:
https://router.api.gov.bc.ca/directions.kml?points=-127.49531103801611,59.9628054674934,-125.02044414445844,58.801945582705464&criteria=fastest&distanceUnit=km&routeDescription=usesLakeFerryFastest&apikey=xxxxxx
produces these directions
•Continue onto Alaska Hwy for 66 km
•Continue onto Hwy 97 for 150 m
•Continue onto Alaska Hwy for 31 km
•Continue onto Hwy 97 for 60 m
•Continue onto Alaska Hwy for 29 km
•Continue onto Hwy 97 for 350 m
•Continue onto Alaska Hwy for 25 km
•Continue onto Hwy 97 for 20 m
•Continue onto Alaska Hwy for 4.7 km
•Continue onto Hwy 97 for 55 m
•Continue onto Alaska Hwy for 54 km
•Continue onto Hwy 97 for 35 m
•Continue onto Alaska Hwy for 6.8 km
•Continue onto Hwy 97 for 70 m
•Continue onto Alaska Hwy for 6.9 km
•Continue onto Hwy 97 for 40 m
•Continue onto Alaska Hwy for 24 km
•Continue onto Hwy 97 for 150 m
•Continue onto Alaska Hwy for 13 km
•Finish!

**Comment by cmhodgson** [comment]
If you run the same query against routertst, with the newer data, you can see that all of the short  "Hwy 97" segments are actually bridges:
Continue onto Alaska Hwy for 66 km
Continue onto Coal River Bridge for 150 m
Continue onto Alaska Hwy for 31 km
Continue onto Smith River Bridge for 60 m
Continue onto Alaska Hwy for 29 km
Continue onto Lower Liard River Bridge for 350 m
Continue onto Alaska Hwy for 25 km
Continue onto Prochniak Creek Bridge for 20 m
Continue onto Alaska Hwy for 4.7 km
Continue onto Trout River Bridge for 55 m
Continue onto Alaska Hwy for 54 km
Continue onto Peterson Creek Bridge for 35 m
Continue onto Alaska Hwy for 6.8 km
Continue onto Toad River Bridge for 70 m
Continue onto Alaska Hwy for 6.9 km
Continue onto 150 Creek Bridge for 40 m
Continue onto Alaska Hwy for 24 km
Continue onto Racing River Bridge for 150 m
Continue onto Alaska Hwy for 13 km
Finish!

**Comment by gleeming** [comment]
Those directions match with the primary names as provided by GeoBC in the Feb. ITN data used in prod.

**Comment by mraross** [comment]
Verified
