### ISSUE TITLE
in address prep, when duplicates occur, choose the bc assessment point

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#98]
BC Assessment address location specifications call for rooftop or front-door points, not just parcel points as is the case with most address authorities.  If an address has a duplicate BC Assessment address, use the bc assessment address location.

**Comment by gleeming** [comment]
Precedent order for duplicate resolution is now: BCA, AddressBC, open/other

**Comment by mraross** [comment]
Doesn't look like BC Assessment parcel points in Surrey. See:

    2541 163 St, Surrey, BC

Please confirm source of this address point.

**Comment by gleeming** [comment]
Source is BC Assessment, so the updated logic is working correctly.  The screenshot shows the August BCA points in the area.  Address location for 2541 163 St is highlighted in blue for the BCA source and I created the green point from coordinates in the ICIS AddressBC CSV file.

![image](https://cloud.githubusercontent.com/assets/21045965/25761185/df8bb798-318e-11e7-980d-2c54ffb6dd22.png)

**Comment by mraross** [comment]
Verified
